# coding: utf-8
def SmilesFromName(input):
    return {
			'ethene' : 'C=C',
			'propanal' : 'CCC=O',	
			'octachlorodirhenate' : '[Rh-](Cl)(Cl)(Cl)(Cl)$[Rh-](Cl)(Cl)(Cl)Cl',
			'water' : 'O',
			'urea' : 'C(=O)(N)N',
			'rubidium oxide' : 'Rb2O',
			'acetaldehyde' : 'CC=O',   
			'acetamide' : ' CC(=O)N',
			'acetaminophen' : 'CC(=O)NC1=CC=C(C=C1)O',
			'acetic acid' : 'CC(=O)O',	
			'acetone' : 'CC(=O)C',		
			'acetylene' : 'C#C',			
			'acetylsalicylic acid' : 'CC(=O)OC1=CC=CC=C1C(=O)O',
			'Aspirin' : 'CC(=O)OC1=CC=CC=C1C(=O)O',
			'adenosine' : 'C1=NC2=C(C(=N1)N)N=CN2C3C(C(C(O3)CO)O)O',
			'adrenaline' : 'CNCC(C1=CC(=C(C=C1)O)O)O',
			'epinephrine' : 'CNCC(C1=CC(=C(C=C1)O)O)O',			
			'alanine' : 'CC(C(=O)O)N',		
			'amoxicillin' : 'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C',  
			'Amphetamine' : 'CC(CC1=CC=CC=C1)N',	
			'angelic acid' : 'CC=C(C)C(=O)O',			
			'anthracene' : 'C1=CC=C2C=C3C=CC=CC3=CC2=C1',		
			'ascorbic acid' : 'C(C(C1C(=C(C(=O)O1)O)O)O)O',			
			'barbituric acid' : 'C1C(=O)NC(=O)NC1=O',		
			'benzene' : 'C1=CC=CC=C1',		
			'benzofuran' : 'C1=CC=C2C(=C1)C=CO2',			
			'benzoic acid' : 'C1=CC=C(C=C1)C(=O)O',			
			'biotin' : 'C1C2C(C(S1)CCCCC(=O)O)NC(=O)N2',		
			'bromocresol purple' : 'CC1=C(C(=CC(=C1)C2(C3=CC=CC=C3S(=O)(=O)O2)C4=CC(=C(C(=C4)Br)O)C)Br)O',				
			'bromoform' : 'C(Br)(Br)Br',	
			'butane' : 'CCCC',			
			'butene' : 'CCC=C',				
			'cadaverine' : 'C(CCN)CCN',			
			'caffeine' : 'CN1C=NC2=C1C(=O)N(C(=O)N2C)C',			
			'vitamin D3' : 'CC(C)CCCC(C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C',	
			'cholecalciferol' : 'CC(C)CCCC(C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C',	
			'capsaicin' : 'CC(C)C=CCCCCC(=O)NCC1=CC(=C(C=C1)O)OC',		
			'captan' : 'C1C=CCC2C1C(=O)N(C2=O)SC(Cl)(Cl)Cl',			
			'cholesterol' : 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C',
			'choline' : 'C[N+](C)(C)CCO',		
			'citric acid' : 'C(C(=O)O)C(CC(=O)O)(C(=O)O)O',		
			'decane' : 'CCCCCCCCCC',			
			'dopamine' : 'C1=CC(=C(C=C1CCN)O)O',		
			'edta' : 'C(CN(CC(=O)O)CC(=O)O)N(CC(=O)O)CC(=O)O',			
			'epinephrine' : 'CNCC(C1=CC(=C(C=C1)O)O)O',			
			'ethane' : 'CC',				
			'ethanol' : 'CCO',		
			'ethylene' : 'C=C',			
			'folic Acid' : 'C1=CC(=CC=C1C(=O)NC(CCC(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)N=C(N3)N',
			'formaldehyde' : 'C=O',	
			'formic Acid' : 'C(=O)O',			
			'furan ' : 'C1=COC=C1',	
			'glucose' : 'C(C1C(C(C(C(O1)O)O)O)O)O',		
			'glutathione' : 'C(CC(=O)NC(CS)C(=O)NCC(=O)O)C(C(=O)O)N',
			'glycine' : 'C(C(=O)O)N',				
			'glycogen' : 'C(C1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3C(OC(C(C3O)O)O)CO)O)O)OC4C(C(C(C(O4)CO)O)O)O)O)O)O)O',		
			'guanosine' : 'C1=NC2=C(N1C3C(C(C(O3)CO)O)O)NC(=NC2=O)N',			
			'heptane' : 'CCCCCCC',	
			'hexane' : 'CCCCCC',			
			'histamine' : 'C1=C(NC=N1)CCN',			
			'ibuprofen' : 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O',			
			'isopropanol' : 'CC(C)O',			
			'kojic acid' : 'C1=C(OC=C(C1=O)O)CO',			
			'lactose' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',		
			'lauric Acid' : 'CCCCCCCCCCCC(=O)O',			
			'LSD' : 'CCN(CC)C(=O)C1CN(C2CC3=CNC4=CC=CC(=C34)C2=C1)C',			
			'lycopene' : 'CC(=CCCC(=CC=CC(=CC=CC(=CC=CC=C(C)C=CC=C(C)C=CC=C(C)CCC=C(C)C)C)C)C)C ',		
			'malic Acid' : 'C(C(C(=O)O)O)C(=O)O',				
			'melatonin' : 'CC(=O)NCCC1=CNC2=C1C=C(C=C2)OC',	
			'menthol' : 'CC1CCC(C(C1)O)C(C)C',			
			'methane' : 'C',			
			'naphthalene' : 'C1=CC=C2C=CC=CC2=C1',			
			'niacin' : 'C1=CC(=CN=C1)C(=O)O',			
			'nicotine' : 'CN1CCCC1C2=CN=CC=C2',		
			'nonane' : 'CCCCCCCCC',			
			'octane' : 'CCCCCCCC',			
			'oxalic acid' : 'C(=O)(C(=O)O)O',			
			'pentane' : 'CCCCC',			
			'phenol' : 'C1=CC=C(C=C1)O',		
			'phenolphthalein' : 'C1=CC=C2C(=C1)C(=O)OC2(C3=CC=C(C=C3)O)C4=CC=C(C=C4)O',			
			'phthalicaAcid' : 'C1=CC=C(C(=C1)C(=O)O)C(=O)O',			
			'progesterone' : 'CC(=O)C1CCC2C1(CCC3C2CCC4=CC(=O)CCC34C)C',	
			'propane' : 'CCC',		
			'purine' : 'C1=C2C(=NC=N1)N=CN2',		
			'pyridine' : 'C1=CC=NC=C1',		
			'pyruvic Acid' : 'CC(=O)C(=O)O',			
			'quinoline' : 'C1=CC=C2C(=C1)C=CC=N2',	    	
			'retinol' : 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C',			
			'riboflavin' : 'CC1=CC2=C(C=C1C)N(C3=NC(=O)NC(=O)C3=N2)CC(C(C(CO)O)O)O',			
			'salicylic Acid' : 'C1=CC=C(C(=C1)C(=O)O)O',		
			'stearic Acid' : 'CCCCCCCCCCCCCCCCCC(=O)O',	
			'sucrose' : 'C(C1C(C(C(C(O1)OC2(C(C(C(O2)CO)O)O)CO)O)O)O)O',		
			'tartaric acid' : 'C(C(C(=O)O)O)(C(=O)O)O',			
			'taurine' : 'C(CS(=O)(=O)O)N',		
			'testosterone' : 'CC12CCC3C(C1CCC2O)CCC4=CC(=O)CCC34C',			
			'thiamine' : 'CC1=C(SC=[N+]1CC2=CN=C(N=C2N)C)CCO',		
			'thymol' : 'CC1=CC(=C(C=C1)C(C)C)O',			
			'toluene' : 'CC1=CC=CC=C1',			
			'urea' : 'C(=O)(N)N',			
			'warfarin' : 'CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O',
			'water' : 'O',
			'N-butylamine' : 'CCCCN', 
			'ethene' : 'C=C',
			'hydrogen cyanide' : 'C#N',		
			'2-butyne' : 'CC#CC',		
			'propanal' : 'CCC=O',		
			'octachlorodirhenate (III)' : '[Rh-](Cl)(Cl)(Cl)(Cl)$[Rh-](Cl)(Cl)(Cl)Cl',		
			'2-ethyl-1-butanol' : 'CCC(CC)CO',	
			'2,4-dimethyl-3-pentanone' : 'CC(C)C(=O)C(C)C',
			'2-propyl-3-isopropyl-1-propanol' : 'OCC(CCC)C(C(C)C)CCC',	
			'thiosulfate' : 'OS(=O)(=S)O',	
			'perhydroisoquinoline' : 'N1CC2CCCC2CC1',
			'benzene' : 'C1=CC=CC=C1',	
			'indane' : 'C1=CC=CC(CCC2)=C12',
			'cyclobutadiene' : 'C1=CC=C1',	
			'hydronium cation' : '[OH3+]',	
			'deuterium oxide' : '[2H]O[2H]',	
			'Heavy Water' : '[2H]O[2H]',	
			'carbon dioxide' : 'O=C=O',
			'hydrogen cyanide' : 'C#N',	
			'decalin' : 'C1CC2CCCCC2CC1',	
			'sodium phenoxide' : '[Na+].[O-]c1ccccc1',	
			'nitrobenzene' : 'c1ccccc1[N+](=O)[O-]',	
			'L-alanine' : 'N[C@@H](C)C(=O)O',
			'cis-resorcinol' : 'O[C@H]1CCCC[C@H]1O',
			'abietic acid' : 'CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C ',   
			'acenaphthene' : 'C1CC2=CC=CC3=C2C1=CC=C3',
			'acenaphthoquinone' : 'C1=CC2=C3C(=C1)C(=O)C(=O)C3=CC=C2',
			'acenaphthylene' : 'C1=CC2=C3C(=C1)C=CC3=CC=C2',
			'acepromazine' : 'CC(=O)C1=CC2=C(C=C1)SC3=CC=CC=C3N2CCCN(C)C',
			'acetaminosalol' : 'CC(=O)NC1=CC=C(C=C1)OC(=O)C2=CC=CC=C2O',
			'acetamiprid' : 'CC(=NC#N)N(C)CC1=CN=C(C=C1)Cl',
			'acetanilide' :  'CC(=O)NC1=CC=CC=C1',
			'acetoguanamine' : 'CC1=NC(=NC(=N1)N)N',
			'acetonitrile' : 'CC#N',
			'acetophenone' : 'CC(=O)C1=CC=CC=C1',
			'acetylcholine' : 'CC(=O)OCC[N+](C)(C)C',    
			'N-acetylglutamate' : 'CC(=O)N[C@@H](CCC(=O)O)C(=O)O',
			'acid fuchsin' :    'CC1=CC(=C(C2=CC(=C(C=C2)N)S(=O)(=O)O)C3=CC(=C(C=C3)N)S(=O)(=O)[O-])C=C(C1=N)S(=O)(=O)[O-].[Na+].[Na+]',
			'acridine orange' : 'CN(C)C1=CC2=C(C=C1)C=C3C=CC(=CC3=N2)N(C)C',
			'acrolein' : 'C=CC=O',
			'acrylamide' : 'C=CC(=O)N',
			'acrylic acid' : 'C=CC(=O)O',
			'acrylonitrile' : 'C=CC#N',
			'acryloyl chloride' : 'C=CC(=O)Cl',
			'acyclovir' : 'C1=NC2=C(N1COCCO)NC(=NC2=O)N',
			'adamantane' : 'C1C2CC3CC1CC(C2)C3',    
			'adipamide' : 'C(CCC(=O)N)CC(=O)N',
			'adipic acid' : 'C(CCC(=O)O)CC(=O)O',
			'adiponitrile' : 'C(CCC#N)CC#N', 
			'adipoyl dichloride ' : 'C(CCC(=O)Cl)CC(=O)Cl',
			'adonitol' : 'C([C@H](C([C@H](CO)O)O)O)O',
			'adrenochrome' : 'CN1CC(C2=CC(=O)C(=O)C=C21)O',
			'albumins' : 'C(C(F)(F)F)(C(F)(F)F)(F)F',
			'alcian blue' : 'CN(C)C(=[N+](C)C)SCC1=CC2=C(C=C1)C3=NC4=NC(=NC5=C6C=C(C=CC6=C([N-]5)N=C7C8=C(C=CC(=C8)CSC(=[N+](C)C)N(C)C)C(=N7)N=C2[N-]3)CSC(=[N+](C)C)N(C)C)C9=C4C=C(C=C9)CSC(=[N+](C)C)N(C)C.[Cl-].[Cl-].[Cl-].[Cl-].[Cu+2]',  
			'aldosterone' : 'CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4C(=O)CO)C=O)O',
			'aldrin' : 'C1C2C=CC1C3C2C4(C(=C(C3(C4(Cl)Cl)Cl)Cl)Cl)Cl',
			'alizarin': 'C1=CC=C2C(=C1)C(=O)C3=C(C2=O)C(=C(C=C3)O)O' ,
			'allantoic acid' : 'C(C(=O)O)(NC(=O)N)NC(=O)N',
			'allantoin' : 'C1(C(=O)NC(=O)N1)NC(=O)N',
			'allethrin' : 'CC1=C(C(=O)CC1OC(=O)C2C(C2(C)C)C=C(C)C)CC=C',
			'allyl propyl disulfide' : 'CCCSSCC=C',
			'allylamine' : 'C=CCN',
			'P-aminobenzoic acid' : 'C1=CC(=CC=C1C(=O)O)N',
			'N-aminoethylpiperazine' : 'C1CN(CCN1)CCN',
			'aminophylline' : 'CN1C2=C(C(=O)N(C1=O)C)NC=N2.CN1C2=C(C(=O)N(C1=O)C)NC=N2.C(CN)N',
			'5-aminosalicylic acid' : 'C1=CC(=C(C=C1N)C(=O)O)O',
			'amiodarone' : 'CCCCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C(=C3)I)OCCN(CC)CC)I',
			'amiton' : 'CCN(CC)CCSP(=O)(OCC)OCC',
			'amobarbital' : 'CCC1(C(=O)NC(=O)NC1=O)CCC(C)C',
			'amyl Nitrate' : 'CCCCCO[N+](=O)[O-]',
			'anethole' : 'CC=CC1=CC=C(C=C1)OC',
			'anilazine' : 'C1=CC=C(C(=C1)NC2=NC(=NC(=N2)Cl)Cl)Cl',
			'aniline' : 'C1=CC=C(C=C1)N',
			'aniline hydrochloride' : 'C1=CC=C(C=C1)N.Cl',
			'anisole' : 'COC1=CC=CC=C1',
			'anthanthrene' : 'C1=CC2=C3C(=C1)C=C4C=CC5=C6C4=C3C(=CC6=CC=C5)C=C2',
			'anthranilic acid' : 'C1=CC=C(C(=C1)C(=O)O)N',
			'anthraquinone' : 'C1=CC=C2C(=C1)C(=O)C3=CC=CC=C3C2=O',
			'anthrone' : 'C1C2=CC=CC=C2C(=O)C3=CC=CC=C31',
			'antipyrine' : 'CC1=CC(=O)N(N1C)C2=CC=CC=C2',
			'aprotinin' : 'CCC(C)C1C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NCC(=O)NC(C(=O)NC2CSSCC3C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(CSSCC(C(=O)NC(C(=O)NC(C(=O)N4CCCC4C(=O)N5CCCC5C(=O)NC(C(=O)NC(C(=O)NCC(=O)N6CCCC6C(=O)NC(CSSCC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)NC(C(=O)N3)CC(=O)O)CCC(=O)O)C)CO)CCCCN)CC7=CC=CC=C7)CC(=O)N)CC(=O)N)CCCNC(=N)N)CCCCN)C)CCCNC(=N)N)NC(=O)CNC(=O)CNC(=O)C(NC(=O)C(NC(=O)C(NC(=O)C(NC(=O)C(NC2=O)CCC(=O)N)C(C)O)CC8=CC=CC=C8)C(C)C)CC9=CC=C(C=C9)O)C(=O)NC(C(=O)NC(C(=O)NC(C(=O)N1)CCCNC(=N)N)C)CCCCN)C(C)O)CC1=CC=C(C=C1)O)CCC(=O)O)CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C(CC(=O)O)NC(=O)C1CCCN1C(=O)C(CCCNC(=N)N)N)C(=O)NCC(=O)NCC(=O)NC(C)C(=O)O)C(C)O)CCCNC(=N)N)CCSC)CC(C)C)C)CCCCN)C)CC(=O)N)CC1=CC=C(C=C1)O)CC1=CC=CC=C1)CC1=CC=C(C=C1)O)CCCNC(=N)N)C(C)CC',
			'arginine' : 'C(C[C@@H](C(=O)O)N)CN=C(N)N',
			'asparagine' : 'C([C@@H](C(=O)O)N)C(=O)N',
			'asparagusic acid' : 'C1C(CSS1)C(=O)O',
			'aspartame' : 'COC(=O)[C@H](CC1=CC=CC=C1)NC(=O)[C@H](CC(=O)O)N',
			'atrazine' : 'CCNC1=NC(=NC(=N1)Cl)NC(C)C',
			'auramine O' : 'CN(C)C1=CC=C(C=C1)C(=N)C2=CC=C(C=C2)N(C)C.Cl',
			'avobenzone' : 'CC(C)(C)C1=CC=C(C=C1)C(=O)CC(=O)C2=CC=C(C=C2)OC',
			'azadirachtin a' : 'CC=C(C)C(=O)OC1CC(C2(COC3C2C14COC(C4C(C3O)(C)C56C7CC(C5(O6)C)C8(C=COC8O7)O)(C(=O)OC)O)C(=O)OC)OC(=O)C',
			'azathioprine' : 'CN1C=NC(=C1SC2=NC=NC3=C2NC=N3)[N+](=O)[O-]',
			'azelaic acid' : 'C(CCCC(=O)O)CCCC(=O)O',
			'azinphos-methyl' : 'COP(=S)(OC)SCN1C(=O)C2=CC=CC=C2N=N1',
			'aziridine' : 'C1CN1',
			'azithromycin' : 'CCC1C(C(C(N(CC(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)C)O)(C)O',
			'azobenzene' : 'C1=CC=C(C=C1)N=NC2=CC=CC=C2',
			'azulene' : 'C1=CC=C2C=CC=C2C=C1',
			'bacillomycin' : 'CCCCCCCCC1CC(=O)NC(C(=O)NC(C(=O)NC(C(=O)N2CCCC2C(=O)NC(C(=O)NC(C(=O)NC(C(=O)N1)C(C)O)CO)CCC(=O)O)CC(=O)N)CC3=CC=C(C=C3)O)CC(=O)N',
			'barbital' : 'CCC1(C(=O)NC(=O)NC1=O)CC',
			'behenic acid' : 'CCCCCCCCCCCCCCCCCCCCCC(=O)O',
			'benomyl' : 'CCCCNC(=O)N1C2=CC=CC=C2N=C1NC(=O)OC',
			'benzaldehyde' : 'C1=CC=C(C=C1)C=O',
			'benzamide' : 'C1=CC=C(C=C1)C(=O)N',
			'benzanthrone' : 'C1=CC=C2C(=C1)C3=CC=CC4=C3C(=CC=C4)C2=O',
			'benzethonium chloride' : 'CC(C)(C)CC(C)(C)C1=CC=C(C=C1)OCCOCC[N+](C)(C)CC2=CC=CC=C2.[Cl-]',
			'benzidine' : 'C1=CC(=CC=C1C2=CC=C(C=C2)N)N',
			'benzil' : 'C1=CC=C(C=C1)C(=O)C(=O)C2=CC=CC=C2',
			'benzilic acid' : ' C1=CC=C(C=C1)C(C2=CC=CC=C2)(C(=O)O)O',
			'benzimidazole' : 'C1=CC=C2C(=C1)NC=N2',
			'benzo(A)anthracene' : 'C1=CC=C2C(=C1)C=CC3=CC4=CC=CC=C4C=C32',
			'benzo(C)cinnoline' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N=N2',
			'benzo(A)pyrene' : 'C1=CC=C2C3=C4C(=CC2=C1)C=CC5=C4C(=CC=C5)C=C3',
			'benzo(C)phenanthrene' : 'C1=CC=C2C(=C1)C=CC3=C2C4=CC=CC=C4C=C3',
			'benzo(E)pyrene' : 'C1=CC=C2C(=C1)C3=CC=CC4=C3C5=C(C=CC=C25)C=C4',
			'benzo(Ghi)perylene' : 'C1=CC2=C3C(=C1)C4=CC=CC5=C4C6=C(C=C5)C=CC(=C36)C=C2',
			'benzo(J)fluoranthene' : 'C1=CC=C2C(=C1)C=CC3=C2C4=CC=CC5=C4C3=CC=C5',
			'benzo(K)fluoranthene' : 'C1=CC=C2C=C3C4=CC=CC5=C4C(=CC=C5)C3=CC2=C1',
			'benzocaine' : 'CCOC(=O)C1=CC=C(C=C1)N',
			'benzoin' : 'C1=CC=C(C=C1)C(C(=O)C2=CC=CC=C2)O',
			'benzothiazole' : 'C1=CC=C2C(=C1)N=CS2',
			'benzothiophene' : 'C1=CC=C2C(=C1)C=CS2',
			'benzotriazole' : 'C1=CC2=NNN=C2C=C1', 
			'benzoxazole' : 'C1=CC=C2C(=C1)N=CO2', 
			'benzyl alcohol' : 'C1=CC=C(C=C1)CO',
			'benzyl chloroformate' : 'C1=CC=C(C=C1)COC(=O)Cl',
			'benzylamine' : 'C1=CC=C(C=C1)CN',
			'benzyldimethylamine' : 'CN(C)CC1=CC=CC=C1',
			'betaine' : 'C[N+](C)(C)CC(=O)[O-]',
			'betulin' : 'CC(=C)C1CCC2(C1C3CCC4C5(CCC(C(C5CCC4(C3(CC2)C)C)(C)C)O)C)CO',
			'butylated hydroxytoluene' : 'CC1=CC(=C(C(=C1)C(C)(C)C)O)C(C)(C)C',
			'biphenyl' : 'C1=CC=C(C=C1)C2=CC=CC=C2',
			'2,2-bipyridyl' : 'C1=CC=NC(=C1)C2=CC=CC=N2',
			'bis(chloromethyl) ether' : 'C(OCCl)Cl',
			'bismarck brown Y' : 'C1=CC(=CC(=C1)N=NC2=C(C=C(C=C2)N)N)N=NC3=C(C=C(C=C3)N)N.Cl.Cl',
			'bisphenol A' : 'CC(C)(C1=CC=C(C=C1)O)C2=CC=C(C=C2)O',
			'biuret' : 'C(=O)(N)NC(=O)N',
			'borneol' : 'CC1(C2CCC1(C(C2)O)C)C',
			'brassinolide' : 'CC(C)C(C)C(C(C(C)C1CCC2C1(CCC3C2COC(=O)C4C3(CC(C(C4)O)O)C)C)O)O',
			'bromacil' : 'CCC(C)N1C(=O)C(=C(NC1=O)C)Br',
			'bromoacetic acid' : 'C(C(=O)O)Br',
			'bromobenzene' : 'C1=CC=C(C=C1)Br',
			'2-bromo-1-chloropropane' : 'CC(CCl)Br',
			'bromocyclohexane' : 'C1CCC(CC1)Br',
			'bromomethane' : 'CBr',
			'bromophenol blue' : 'C1=CC=C2C(=C1)C(OS2(=O)=O)(C3=CC(=C(C(=C3)Br)O)Br)C4=CC(=C(C(=C4)Br)O)Br',
			'2-bromopropane' : 'CC(C)Br',
			'bromothymol blue' : 'CC1=C(C(=C(C=C1C2(C3=CC=CC=C3S(=O)(=O)O2)C4=CC(=C(C(=C4C)Br)O)C(C)C)C(C)C)O)Br',
			'bromotrifluoromethane' : 'C(F)(F)(F)Br',
			'brucine' : 'COC1=C(C=C2C(=C1)C34CCN5C3CC6C7C4N2C(=O)CC7OCC=C6C5)OC',
			'buckminsterfullerene' : 'C12=C3C4=C5C6=C1C7=C8C9=C1C%10=C%11C(=C29)C3=C2C3=C4C4=C5C5=C9C6=C7C6=C7C8=C1C1=C8C%10=C%10C%11=C2C2=C3C3=C4C4=C5C5=C%11C%12=C(C6=C95)C7=C1C1=C%12C5=C%11C4=C3C3=C5C(=C81)C%10=C23',
			'buspirone' : '1,3-Butadiene',
			'2-butoxyethanol' : 'CCCCOCCO',
			'butylamine' : 'CCCCN',
			'butyllithium' : '[Li+].CCC[CH2-]',
			'butyraldehyde' : 'CCCC=O',
			'butyrophenone' : 'CCCC(=O)C1=CC=CC=C1',
			'butyryl chloride' : 'CCCC(=O)Cl',
			'cacodylic acid' : 'C[As](=O)(C)O',
			'cacotheline' : 'C1CN2CC3=CCOC(C4C3CC2C15C4NC6=C(C(=O)C(=O)C=C56)[N+](=O)[O-])CC(=O)O',
			'cafestol' : 'CC12CCC3=C(C1CCC45C2CCC(C4)C(C5)(CO)O)C=CO3',
			'calcein' : 'C1=CC=C2C(=C1)C(=O)OC23C4=CC(=C(C=C4OC5=CC(=C(C=C35)CN(CC(=O)O)CC(=O)O)O)O)CN(CC(=O)O)CC(=O)O',
			'camphene' : 'CC1(C2CCC(C2)C1=C)C',
			'camphor' : 'CC1(C2CCC1(C(=O)C2)C)C',
			'cannabinol' : 'CCCCCC1=CC2=C(C(=C1)O)C3=C(C=CC(=C3)C)C(O2)(C)C',
			'caprolactam' : 'C1CCC(=O)NCC1',
			'captopril' : 'CC(CS)C(=O)N1CCCC1C(=O)O',
			'carbazole' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N2',
			'carbazol-9-yl-methanol' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N2CO',
			'carbofuran' : 'CC1(CC2=C(O1)C(=CC=C2)OC(=O)NC)C',
			'carbonyl fluoride' : 'C(=O)(F)F',
			'carboplatin' : 'C1CC(C1)(C(=O)O)C(=O)O.N.N.[Pt]',
			'carminic acid' : 'CC1=C2C(=CC(=C1C(=O)O)O)C(=O)C3=C(C2=O)C(=C(C(=C3O)O)C4C(C(C(C(O4)CO)O)O)O)O',
			'cartap' : 'CN(C)C(CSC(=O)N)CSC(=O)N',
			'carvacrol' : 'CC1=C(C=C(C=C1)C(C)C)O',
			'carvone' : 'CC1=CCC(CC1=O)C(=C)C',
			'castor Oil' : 'CCCCCCC(CC=CCCCCCCCC(=O)OCC(COC(=O)CCCCCCCC=CCC(CCCCCC)O)OC(=O)CCCCCCCC=CCC(CCCCCC)O)O',
			'catechol' : 'C1=CC=C(C(=C1)O)O',
			'cefazolin' : 'CC1=NN=C(S1)SCC2=C(N3C(C(C3=O)NC(=O)CN4C=NN=N4)SC2)C(=O)O',
			'cefotaxime' : 'CC(=O)OCC1=C(N2C(C(C2=O)NC(=O)C(=NOC)C3=CSC(=N3)N)SC1)C(=O)O',
			'ceftriaxone' : 'CN1C(=NC(=O)C(=O)N1)SCC2=C(N3C(C(C3=O)NC(=O)C(=NOC)C4=CSC(=N4)N)SC2)C(=O)O',
			'cetrimide' : 'CCCCCCCCCCCCCC[N+](C)(C)C',
			'cetyl alcohol' : 'CCCCCCCCCCCCCCCCO',
			'chloracetyl chloride' : 'C(C(=O)Cl)Cl',
			'chloral' : 'C(=O)C(Cl)(Cl)Cl',
			'chloral hydrate' : 'C(C(Cl)(Cl)Cl)(O)O',
			'chlorambucil' : 'C1=CC(=CC=C1CCCC(=O)O)N(CCCl)CCCl',
			'chloramine-T' : 'CC1=CC=C(C=C1)S(=O)(=O)[N-]Cl.[Na+]',
			'chloramphenicol' : 'C1=CC(=CC=C1C(C(CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-]',
			'chloranilic acid' : 'C1(=C(C(=O)C(=C(C1=O)Cl)O)Cl)O',
			'chlordane' : 'C1C2C(C(C1Cl)Cl)C3(C(=C(C2(C3(Cl)Cl)Cl)Cl)Cl)Cl',
			'chlorhexidine gluconate' : 'C1=CC(=CC=C1NC(=NC(=NCCCCCCN=C(N)N=C(N)NC2=CC=C(C=C2)Cl)N)N)Cl',
			'chloro-M-cresol' : 'CC1=CC(=CC(=C1)Cl)O',
			'chloroacetic acid' : 'C(C(=O)O)Cl',
			'4-chloroaniline' : 'C1=CC(=CC=C1N)Cl',
			'chlorobenzene' : 'C1=CC=C(C=C1)Cl',
			'2-chlorobenzoic acid' : 'C1=CC=C(C(=C1)C(=O)O)Cl',
			'chlorodifluoromethane' : 'C(F)(F)Cl',
			'chloroethene' : 'C=CCl',
			'chlorofluoromethane' : 'C(F)Cl',
			'chloroform' : 'C(Cl)(Cl)Cl',
			'chloromethane' : 'CCl',
			'2-chloro-2-methylpropane' : 'CC(C)(C)Cl',
			'chloronitroaniline' : 'C1=CC=C(C=C1)N([N+](=O)[O-])Cl',
			'chloropentafluoroethane' : 'C(C(F)(F)Cl)(F)(F)F',
			'chloropicrin' : 'C([N+](=O)[O-])(Cl)(Cl)Cl',
			'chloroprene' : 'C=CC(=C)Cl',
			'chloroquine' : 'CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl',
			'chlorostyrene' : 'C1=CC=C(C=C1)C=CCl',
			'chlorothiazide' : 'C1=C2C(=CC(=C1Cl)S(=O)(=O)N)S(=O)(=O)N=CN2',
			'chlorotrifluoromethane' : 'C(F)(F)(F)Cl',
			'chlorotrimethylsilane' : 'C[Si](C)(C)Cl',
			'chloroxuron' : 'CN(C)C(=O)NC1=CC=C(C=C1)OC2=CC=C(C=C2)Cl',
			'chlorpyrifos' : 'CCOP(=S)(OCC)OC1=NC(=C(C=C1Cl)Cl)Cl',
			'chlorthiamide' : 'C1=CC(=C(C(=C1)Cl)C(=S)N)Cl',
			'chromotropic acid' : 'C1=C2C=C(C=C(C2=C(C=C1S(=O)(=O)O)O)O)S(=O)(=O)O',
			'cilostazol' : 'C1CCC(CC1)N2C(=NN=N2)CCCCOC3=CC4=C(C=C3)NC(=O)CC4',
			'cinchonine' : 'C=CC1CN2CCC1CC2C(C3=CC=NC4=CC=CC=C34)O',
			'cinnamaldehyde' : 'C1=CC=C(C=C1)C=CC=O',
			'cinnamic acid' : 'C1=CC=C(C=C1)C=CC(=O)O',
			'cinnamyl alcohol' : 'C1=CC=C(C=C1)C=CCO',
			'cinnoline' : 'C1=CC=C2C(=C1)C=CN=N2',
			'cis-2-butene' : 'CC=CC',
			'cis-3-hexenal' : 'CCC=CCC=O',
			'cis-3-hexen-1-ol' : 'CCC=CCCO',
			'citral' : 'CC(=CCCC(=CC=O)C)C',
			'citronellal' : 'CC(CCC=C(C)C)CC=O',
			'clobetasone' : 'CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(=O)CC2(C1(C(=O)CCl)O)C)F)C',
			'clopidol' : 'CC1=C(C(=O)C(=C(N1)C)Cl)Cl',
			'cloxacillin' : 'CC1=C(C(=NO1)C2=CC=CC=C2Cl)C(=O)NC3C4N(C3=O)C(C(S4)(C)C)C(=O)O',
			'cobalamin' : 'CC1=CC2=C(C=C1C)N(C=N2)C3C(C(C(O3)CO)OP(=O)([O-])OC(C)CNC(=O)CCC4(C(C5C6(C(C(C(=N6)C(=C7C(C(C(=N7)C=C8C(C(C(=N8)C(=C4[N-]5)C)CCC(=O)N)(C)C)CCC(=O)N)(C)CC(=O)N)C)CCC(=O)N)(C)CC(=O)N)C)CC(=O)N)C)O.[Co+3]',
			'cocamidopropyl' : 'CCCCCCCCCCCC(=O)NCCC[N+](C)(C)CC(=O)[O-]',
			'colchicine' : 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC',
			'congo red' : 'C1=CC=C2C(=C1)C(=CC(=C2N)N=NC3=CC=C(C=C3)C4=CC=C(C=C4)N=NC5=C(C6=CC=CC=C6C(=C5)S(=O)(=O)[O-])N)S(=O)(=O)[O-].[Na+].[Na+]',
			'coniine' : 'CCCC1CCCCN1',
			'coronene' : 'C1=CC2=C3C4=C1C=CC5=C4C6=C(C=C5)C=CC7=C6C3=C(C=C2)C=C7',
			'coumarin' : 'C1=CC=C2C(=C1)C=CC(=O)O2',
			'creatine' : 'CN(CC(=O)O)C(=N)N',
			'cresyl violet' : 'CC1=CC2=C(C=C1N(C)C)OC3=CC(=[NH2+])C4=CC=CC=C4C3=N2.[Cl-]',
			'crotonaldehyde' : 'CC=CC=O',
			'18-crown-6' : 'C1COCCOCCOCCOCCOCCO1',
			'crystal violet' : 'CN(C)C1=CC=C(C=C1)C(=C2C=CC(=[N+](C)C)C=C2)C3=CC=C(C=C3)N(C)C.[Cl-]',
			'cubane' : 'C12C3C4C1C5C2C3C45',
			'cumene' : 'CC(C)C1=CC=CC=C1',
			'cuneane' : 'C12C3C4C3C5C4C1C25',
			'cupferron' : 'C1=CC=C(C=C1)N(N=O)[O-].[NH4+]',
			'cuscohygrine' : 'CN1CCCC1CC(=O)CC2CCCN2C',
			'cyanogen' : 'C(#N)C#N',
			'cyanogen chloride' : 'C(#N)Cl',
			'cyanoguanidine' : 'C(#N)N=C(N)N',
			'cyanuric acid' : 'C1(=O)NC(=O)NC(=O)N1',
			'cyanuric chloride' : 'C1(=NC(=NC(=N1)Cl)Cl)Cl',
			'cyclodecane' : 'C1CCCCCCCCC',
			'αcCyclodextrin' : 'C(C1C2C(C(C(O1)OC3C(OC(C(C3O)O)OC4C(OC(C(C4O)O)OC5C(OC(C(C5O)O)OC6C(OC(C(C6O)O)OC7C(OC(O2)C(C7O)O)CO)CO)CO)CO)CO)O)O)O',
			'cyclododecane' : 'C1CCCCCCCCCCC',
			'cycloheptatriene' : 'C1C=CC=CC=C1',
			'cyclohexane' : 'C1CCCCC',
			'cyclohexanol' : 'C1CCC(CC1)O',
			'cyclohexanone' : 'C1CCC(=O)CC1',
			'cyclohexene' : 'C1CCC=CC1',
			'cyclonite' : 'C1N(CN(CN1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
			'cyclooctatetraene' : 'C1=CC=CC=CC=C1',
			'cyclopentadiene ' : 'C1C=CC=C1',
			'cyclopentane' : 'C1CCCC1',
			'cyclopentanol' : 'C1CCC(C1)O',
			'cyclopentanone' : 'C1CCC(=O)C1',
			'cyclopentene' : 'C1CC=CC1',
			'cypermethrin' : 'CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)C=C(Cl)Cl)C',
			'cysteamine' : 'C(CS)N',
			'cytosine' : 'C1=C(NC(=O)N=C1)N',
			'DDT' : 'C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)C(Cl)(Cl)Cl)Cl',
			'decaborane'  :  '[B][B][B][B][B][B][B][B][B][B]',
			'decabromodiphenyl ether' : 'C1(=C(C(=C(C(=C1Br)Br)Br)Br)Br)OC2=C(C(=C(C(=C2Br)Br)Br)Br)Br',
			'decahydronaphthalene'  :  'C1CCC2CCCCC2C',
			'dehydroacetic acid' : 'CC1=CC(=O)C(C(=O)O1)C(=O)C',
			'dehydrocholic acid' : 'CC(CCC(=O)O)C1CCC2C1(C(=O)CC3C2C(=O)CC4C3(CCC(=O)C4)C)C',
			'deltamethrin' : 'CC1(C(C1C(=O)OC(C#N)C2=CC(=CC=C2)OC3=CC=CC=C3)C=C(Br)Br)C',
			'denatonium' : 'CC[N+](CC)(CC1=CC=CC=C1)CC(=O)NC2=C(C=CC=C2C)C',
			'dexamethazone' : 'CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C',
			'dextran' : 'C(C1C(C(C(C(O1)OCC2C(C(C(C(O2)OCC(C(C(C(C=O)O)O)O)O)O)O)O)O)O)O)O',
			'dextrin' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)OC3C(OC(C(C3O)O)O)CO)CO)O)O)O)O',
			'3,3-diaminobenzidine' : 'C1=CC(=C(C=C1C2=CC(=C(C=C2)N)N)N)N',
			'di-t-butyl peroxide' : ' CC(C)(C)OOC(C)(C)C',
			'diacetylene' : 'C#CC#C',
			'diazinon' : 'CCOP(=S)(OCC)OC1=NC(=NC(=C1)C)C(C)C',
			'diazomethane' : 'C=[N+]=[N-]',
			'1,2-dibromoethane' : 'C(CBr)Br',
			'dibucaine hydrochloride' : 'CCCCOC1=NC2=CC=CC=C2C(=C1)C(=O)NCCN(CC)CC.Cl',
			'dichloroacetic acid' : 'C(C(=O)O)(Cl)Cl',
			'p-dichlorobenzene' : 'C1=CC(=CC=C1Cl)Cl',
			'dichlorobutane' : 'CCCC(Cl)Cl',
			'dichlorodifluoromethane' : 'C(F)(F)(Cl)Cl',
			'dichlorodimethylsilane' : 'C[Si](C)(Cl)Cl',
			'1,2-dichloroethane' : 'C(CCl)Cl',
			'dichlorofluoromethane' : 'C(F)(Cl)Cl',
			'dichlorophen' : 'C1=CC(=C(C=C1Cl)CC2=C(C=CC(=C2)Cl)O)O',
			'2,4-dichlorophenoxyacetic acid' : 'C1=CC(=C(C=C1Cl)Cl)OCC(=O)O',
			'dichlorotrifluoroethane' : 'C(C(F)(F)F)(Cl)Cl',
			'dichlorvos' : 'COP(=O)(OC)OC=C(Cl)Cl',
			'diclofenac sodium' : 'C1=CC=C(C(=C1)CC(=O)[O-])NC2=C(C=CC=C2Cl)Cl.[Na+]',
			'dicofol' : 'C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)(C(Cl)(Cl)Cl)O)Cl',
			'dicrotophos' : 'CC(=CC(=O)N(C)C)OP(=O)(OC)OC',
			'dicyclopentadiene' : 'C1C=CC2C1C3CC2C=C3',
			'dieldrin' : 'C1C2C3C(C1C4C2O4)C5(C(=C(C3(C5(Cl)Cl)Cl)Cl)Cl)Cl',
			'diethanolamine' : 'C(CO)NCCO',
			'diethyl aluminium chloride' : 'CC[Al](CC)Cl',
			'diethylamine' : 'CCNCC',
			'diethylene glycol' : 'C(COCCO)O',
			'diethylenetriamine' : 'C(CNCCN)N',
			'diethyl Ether' : 'CCOCC',
			'difluoromethane' : 'C(F)F',
			'digitonin' : 'CC1CCC2(C(C3C(O2)C(C4C3(CCC5C4CCC6C5(CC(C(C6)OC7C(C(C(C(O7)CO)OC8C(C(C(C(O8)CO)O)OC9C(C(C(CO9)O)O)O)OC2C(C(C(C(O2)CO)O)OC2C(C(C(C(O2)CO)O)O)O)O)O)O)O)C)C)O)C)OC1',
			'dihydrocortisone' : 'CC12CCC(=O)CC1CCC3C2C(=O)CC4(C3CCC4(C(=O)CO)O)C',
			'diisoheptyl phthalate' : 'CC(C)CCCCOC(=O)C1=CC=CC=C1C(=O)OCCCCC(C)C',
			'diisopropyl ether' : 'CC(C)OC(C)C',
			'diketene' : 'C=C1CC(=O)O1',
			'dimethylamine' : 'CNC',
			'N,N-dimethylacetamide' : 'CC(=O)N(C)C',
			'N,N-dimethylaniline' : 'CN(C)C1=CC=CC=C1',
			'1,4-dimethylbenzene' : 'CC1=CC=C(C=C1)C',
			'p-xylene' : 'CC1=CC=C(C=C1)C',
			'N,N-dimethylformamide' : 'CN(C)C=O', 
			'dimethyldiethoxysilane' : 'CCO[Si](C)(C)OCC',
			'dimethylglyoxime' : 'CC(=C(C)N=O)NO',
			'dimethylmercury' : 'C[Hg]C',
			'dimethyl sulfoxide' : 'CS(=O)C',
			'dinoseb' : 'CCC(C)C1=CC(=CC(=C1O)[N+](=O)[O-])[N+](=O)[O-]',
			'dioctyl phthalate' : 'CCCCCCCCOC(=O)C1=CC=CC=C1C(=O)OCCCCCCCC',
			'dioxane' : 'C1COCCO1',
			'dioxathion' : 'CCOP(=S)(OCC)SC1C(OCCO1)SP(=S)(OCC)OCC',
			'dioxin' : 'C1=C2C(=CC(=C1Cl)Cl)OC3=CC(=C(C=C3O2)Cl)Cl',
			'diphenylacetylene' : 'C1=CC=C(C=C1)C#CC2=CC=CC=C2',
			'tolane' : 'C1=CC=C(C=C1)C#CC2=CC=CC=C2',
			'diphenylmethanol' : 'C1=CC=C(C=C1)C(C2=CC=CC=C2)O',
			'benzhydrol' : 'C1=CC=C(C=C1)C(C2=CC=CC=C2)O',
			'diquat' : 'C1C[N+]2=CC=CC=C2C3=CC=CC=[N+]31',
			'direct blue 1' : 'COC1=C(C=CC(=C1)C2=CC(=C(C=C2)NN=C3C=CC4=C(C3=O)C(=C(C=C4S(=O)(=O)[O-])S(=O)(=O)[O-])N)OC)NN=C5C=CC6=C(C5=O)C(=C(C=C6S(=O)(=O)[O-])S(=O)(=O)[O-])N.[Na+].[Na+].[Na+].[Na+]',
			'disulfiram' : 'CCN(CC)C(=S)SSC(=S)N(CC)CC',
			'disulfoton' : 'CCOP(=S)(OCC)SCCSCC',
			'dithranol' : 'C1C2=C(C(=CC=C2)O)C(=O)C3=C1C=CC=C3O',
			'2,6-di-tert-butylpyridine' : 'CC(C)(C)C1=NC(=CC=C1)C(C)(C)C',
			'diuron' : 'CN(C)C(=O)NC1=CC(=C(C=C1)Cl)Cl',
			'divinylbenzene' : 'C=CC1=CC=CC=C1C=C',
			'docosane' : 'CCCCCCCCCCCCCCCCCCCCCC',
			'dodecane' : 'CCCCCCCCCCCC',
			'dodecylbenzene' : 'CCCCCCCCCCCCC1=CC=CC=C1',
			'domperidone' : 'C1CN(CCC1N2C3=C(C=C(C=C3)Cl)NC2=O)CCCN4C5=CC=CC=C5NC4=O',
			'doxylamine succinate' : 'CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C.C(CC(=O)O)C(=O)O',
			'eicosane' : 'CCCCCCCCCCCCCCCCCCCC',
			'endosulfan' : 'C1C2C(COS(=O)O1)C3(C(=C(C2(C3(Cl)Cl)Cl)Cl)Cl)Cl',
			'endrin' : 'C1C2C3C(C1C4C2O4)C5(C(=C(C3(C5(Cl)Cl)Cl)Cl)Cl)Cl',
			'ephedrine' : 'CC(C(C1=CC=CC=C1)O)NC',
			'epibromohydrin' : 'C1C(O1)CBr',
			'erucic acid': 'CCCCCCCCC=CCCCCCCCCCCCC(=O)O',
			'erythritol' : 'C(C(C(CO)O)O)O',
			'estradiol' : 'CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O',
			'ethacridine lactate' : 'CCOC1=CC2=C(C3=C(C=C(C=C3)N)N=C2C=C1)N.CC(C(=O)O)O',
			'1,2-ethanedithiol ' : 'C(CS)S',
			'ethene' : 'C=C',
			'ethidium bromide' : 'CC[N+]1=C2C=C(C=CC2=C3C=CC(=CC3=C1C4=CC=CC=C4)N)N.[Br-]',
			'ethyl acetate' : 'CCOC(=O)C',
			'ethylamine' : 'CCN',
			'ethyl 4-aminobenzoate' : 'CCOC(=O)C1=CC=C(C=C1)N',
			'ethyl p-aminobenzoate' : 'CCOC(=O)C1=CC=C(C=C1)N',
			'ethylbenzene' : ' CCC1=CC=CC=C1',
			'ethyl chloride' : 'CCCl',
			'ethylene glycol' : 'C(CO)O',
			'ethylene oxide' : 'C1CO1',
			'ethyl formate' : 'CCOC=O',
			'2-ethyl-1-hexanol' : 'CCCCC(CC)CO',
			'eugenol' : 'COC1=C(C=CC(=C1)CC=C)O',
			'farnesol' : 'CC(=CCCC(=CCCC(=CCO)C)C)C',
			'fipronil' : 'C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)S(=O)C(F)(F)F)N)Cl)C(F)(F)F',
			'flunixin' : 'CC1=C(C=CC=C1NC2=C(C=CC=N2)C(=O)O)C(F)(F)F',
			'fluoranthene' : 'C1=CC=C2C(=C1)C3=CC=CC4=C3C2=CC=C4',
			'fluorene' : 'C1C2=CC=CC=C2C3=CC=CC=C31',
			'9-fluorenone' : 'C1=CC=C2C(=C1)C3=CC=CC=C3C2=O',
			'fluorescein' : 'C1=CC=C2C(=C1)C(=O)OC23C4=C(C=C(C=C4)O)OC5=C3C=CC(=C5)O',
			'fluorobenzene' : 'C1=CC=C(C=C1)F',
			'fluoroethylene' : 'C=CF',
			'fluoxetine' : 'CNCCC(C1=CC=CC=C1)OC2=CC=C(C=C2)C(F)(F)F',
			'fonofos' : 'CCOP(=S)(CC)SC1=CC=CC=C1',
			'formamide' : 'C(=O)N',
			'formanilide' : 'C1=CC=C(C=C1)NC=O',
			'formoterol' : 'CC(CC1=CC=C(C=C1)OC)NCC(C2=CC(=C(C=C2)O)NC=O)O',
			'fumaric acid' : 'C(=CC(=O)O)C(=O)O',
			'furfural' : 'C1=COC(=C1)C=O',
			'furfuryl alcohol' : 'C1=COC(=C1)CO',
			'furfurylamine' : 'C1=COC(=C1)CN',
			'furylfuramide' : 'C1=COC(=C1)C(=CC2=CC=C(O2)[N+](=O)[O-])C(=O)N',
			'gadopentetate' : 'C(CN(CC(=O)O)CC(=O)[O-])N(CCN(CC(=O)O)CC(=O)[O-])CC(=O)[O-].[Gd+3]',
			'galantamine' : 'CN1CCC23C=CC(CC2OC4=C(C=CC(=C34)C1)OC)O',
			'gamma-aminobutyric acid' : 'C(CC(=O)O)CN',
			'gamma-butyrolactone' : 'C1CC(=O)OC1',
			'gamma-hydroxybutyrate' : 'C(CC(=O)O)CO',
			'GHB' : 'C(CC(=O)O)CO',
			'geraniol' : 'CC(=CCCC(=CCO)C)C',
			'gibberellic acid' : 'CC12C(C=CC3(C1C(C45C3CCC(C4)(C(=C)C5)O)C(=O)O)OC2=O)O',
			'gluconic acid' : 'C(C(C(C(C(C(=O)O)O)O)O)O)O',\
			'glutamine' : 'C(CC(=O)N)C(C(=O)O)N',
			'glutaraldehyde' : 'C(CC=O)CC=O',
			'glutaric acid' : 'C(CC(=O)O)CC(=O)O',
			'glyburide' : 'COC1=C(C=C(C=C1)Cl)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=O)NC3CCCCC3',
			'glycerin' : 'C(C(CO)O)O',
			'glycerol' : 'C(C(CO)O)O',
			'glycerophosphoric acid' : 'C(C(COP(=O)(O)O)O)O',
			'glycidol' : 'C1C(O1)CO',
			'glycolic acid' : 'C(C(=O)O)O',
			'glyoxal' : 'C(=O)C=O',
			'guaiacol' : 'COC1=CC=CC=C1O',
			'guanine' : 'C1=NC2=C(N1)C(=O)N=C(N2)N',
			'halothane' : 'C(C(F)(F)F)(Cl)Br',
			'hematoxylin' : 'C1C2=CC(=C(C=C2C3C1(COC4=C3C=CC(=C4O)O)O)O)O',
			'hepes' : 'C1CN(CCN1CCO)CCS(=O)(=O)O',
			'heptadecane' : 'CCCCCCCCCCCCCCCCC',
			'hexabromocyclododecane' : 'C1CC(C(CCC(C(CCC(C1Br)Br)Br)Br)Br)Br',
			'hexachloropropene' : 'C(=C(Cl)Cl)(C(Cl)(Cl)Cl)Cl',
			'hexadecane' : 'CCCCCCCCCCCCCCCC',
			'hexafluoro-2-propanol' : 'C(C(F)(F)F)(C(F)(F)F)O',
			'hexafluoro-2-propanone' : 'C(=O)(C(F)(F)F)C(F)(F)F',
			'hexafluoroethane' : 'C(C(F)(F)F)(F)(F)F',
			'hexafluoropropylene' : 'C(=C(F)F)(C(F)(F)F)F',
			'hexamethyldewarbenzene' : 'CC1=C(C2(C1(C(=C2C)C)C)C)C',
			'hexamethyldisilazane' : 'C[Si](C)(C)N[Si](C)(C)C',
			'hexamethylenimine' : 'C1CCCNCC1',
			'hexamethylolmelamine' : 'C(N(CO)C1=NC(=NC(=N1)N(CO)CO)N(CO)CO)O',
			'hexamine' : 'C1N2CN3CN1CN(C2)C3',
			'hexanitrodiphenylamine' : 'C1=C(C=C(C(=C1[N+](=O)[O-])NC2=C(C=C(C=C2[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
			'hexanoic acid' : 'CCCCCC(=O)O',
			'cis-3-hexanal' : 'CCC=CCC=O',
			'cis-3-hexen-1-ol' : 'CCC=CCCO',
			'hippuric acid' : 'C1=CC=C(C=C1)C(=O)NCC(=O)O',
			'histidine' : 'C1=C(NC=N1)CC(C(=O)O)N',
			'homoarginine' : 'C(CCN=C(N)N)CC(C(=O)O)N',
			'homocysteine' : 'C(CS)C(C(=O)O)N',
			'homocystine' : 'C(CSSCCC(C(=O)O)N)C(C(=O)O)N',
			'homotaurine' : 'C(CN)CS(=O)(=O)O',
			'hydrochlorothiazide' : 'C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl',
			'hydroquinone' : 'C1=CC(=CC=C1O)O',
			'hydroxyproline' : 'C1C(CNC1C(=O)O)O',
			'5-hydroxytryptamine' : 'C1=CC2=C(C=C1O)C(=CN2)CCN',
			'hygrine' : 'CC(=O)CC1CCCN1C',
			'imazapyr' : 'CC(C)C1(C(=O)NC(=N1)C2=C(C=CC=N2)C(=O)O)C',
			'imidazole' : 'C1=CN=CN1',
			'imiquimod' : 'CC(C)CN1C=NC2=C1C3=CC=CC=C3N=C2N',
			'indazole' : ' C1=CC=C2C(=C1)C=NN2',
			'indene' : 'C1C=CC2=CC=CC=C21',
			'indigo' : 'C1=CC=C2C(=C1)C(=O)C(=C3C(=O)C4=CC=CC=C4N3)N2',
			'indole' : 'C1=CC=C2C(=C1)C=CN2',
			'indoline' : 'C1CNC2=CC=CC=C21',
			'inositol' : 'C1(C(C(C(C(C1O)O)O)O)O)O',
			'iodoxybenzene' : 'C1=CC=C(C=C1)I(=O)=O',
			'ipratropium bromide' : 'CC(C)[N+]1(C2CCC1CC(C2)OC(=O)C(CO)C3=CC=CC=C3)C.[Br-]',
			'isatin' : 'C1=CC=C2C(=C1)C(=O)C(=O)N2',
			'isoamyl isobutyrate' : 'CC(C)CCOC(=O)C(C)C',
			'isobenzofuran' : 'C1=CC2=COC=C2C=C1',
			'isoborneol' : 'CC1(C2CCC1(C(C2)O)C)C',
			'isobornyl acetate' : 'CC(=O)OC1CC2CCC1(C2(C)C)C',
			'isoflurane' : 'C(C(F)(F)F)(OC(F)F)Cl',
			'isoleucine' : 'CCC(C)C(C(=O)O)N',
			'isomelamine' : 'C1(=NC(=NC(=N1)N)N)N',
			'isooctanol' : 'CC(C)CCCCCO',
			'isophthalic acid' : 'C1=CC(=CC(=C1)C(=O)O)C(=O)O',
			'isoquinoline' : 'C1=CC=C2C=NC=CC2=C1',
			'isoxazole' : 'C1=CON=C1',
			'itraconazole' : 'CCC(C)N1C(=O)N(C=N1)C2=CC=C(C=C2)N3CCN(CC3)C4=CC=C(C=C4)OCC5COC(O5)(CN6C=NC=N6)C7=C(C=C(C=C7)Cl)Cl',
			'jasmone' : 'CCC=CCC1=C(CCC1=O)C',
			'kanamycin' : 'C1C(C(C(C(C1N)OC2C(C(C(C(O2)CN)O)O)O)O)OC3C(C(C(C(O3)CO)O)N)O)N',
			'kepone alcohol' : 'C1(C2(C3(C4(C1(C5(C2(C3(C(C45Cl)(Cl)Cl)Cl)Cl)Cl)Cl)Cl)Cl)Cl)O',
			'ketene' : 'C=C=O',
			'lactic acid' : 'CC(C(=O)O)O',
			'lauryl alcohol' : 'CCCCCCCCCCCCO',
			'lithium diisopropylamide' : '[Li+].CC(C)[N-]C(C)C',
			'deucine' : 'CC(C)CC(C(=O)O)N',
			'levulinic acid' : 'CC(=O)CCC(=O)O',
			'limonene' : 'CC1=CCC(CC1)C(=C)C',
			'linalool' : 'CC(=CCCC(C)(C=C)O)C',
			'linoleic acid' : 'CCCCCC=CCC=CCCCCCCCC(=O)O',
			'linolenic acid' : 'CCC=CCC=CCC=CCCCCCCCC(=O)O',
			'lipoamide' : 'C1CSSC1CCCCC(=O)N',
			'lithium diisopropylamide' : '[Li+].CC(C)[N-]C(C)C',
			'loratadine' : 'CCOC(=O)N1CCC(=C2C3=C(CCC4=C2N=CC=C4)C=C(C=C3)Cl)CC1',
			'luminol' : 'C1=CC2=C(C(=C1)N)C(=O)NNC2=O',
			'lysine' : 'C(CCN)CC(C(=O)O)N',
			'malachite green' : 'CN(C)C1=CC=C(C=C1)C(=C2C=CC(=[N+](C)C)C=C2)C3=CC=CC=C3.[Cl-]',
			'maleic anhydride' : 'C1=CC(=O)OC1=O',
			'maltose' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
			'mandelonitrile' : 'C1=CC=C(C=C1)C(C#N)O',
			'mannose' : 'C(C1C(C(C(C(O1)O)O)O)O)O',
			'mauveine' : 'CC1=CC=C(C=C1)[N+]2=C3C=C(C(=CC3=NC4=C2C=C(C(=C4)C)N)C)NC5=CC=CC=C5',
			'MDMA' : 'CC(CC1=CC2=C(C=C1)OCO2)NC',
			'mecoprop' : 'CC1=C(C=CC(=C1)Cl)OC(C)C(=O)O',
			'MEK' : 'CCC(=O)C',
			'meldolas blue' : 'C[N+](=C1C=CC2=NC3=C(C=CC4=CC=CC=C43)OC2=C1)C.[Cl-].[Cl-].[Cl-].[Zn+2]',
			'meloxicam' : 'CC1=CN=C(S1)NC(=O)C2=C(C3=CC=CC=C3S(=O)(=O)N2C)O',
			'2-mercaptoethanol' : 'C(CS)O',
			'2-mercaptopyridine' : 'C1=CC(=S)NC=C1',
			'merocyanine' : 'CCCCN1C(=O)C(=CC=CC=C2N(C3=CC=CC=C3O2)CCCS(=O)(=O)[O-])C(=O)N(C1=O)CCCC.[Na+]',
			'mesityl oxide' : 'CC(=CC(=O)C)C',
			'mesotartaric acid' : 'C(C(C(=O)O)O)(C(=O)O)O',
			'metaldehyde' : 'CC1OC(OC(OC(O1)C)C)C',
			'metamizole' : 'CC1=C(C(=O)N(N1C)C2=CC=CC=C2)N(C)CS(=O)(=O)[O-].[Na+]',
			'dipyrone' : 'CC1=C(C(=O)N(N1C)C2=CC=CC=C2)N(C)CS(=O)(=O)[O-].[Na+]',
			 'methanesulfonic acid' : 'CS(=O)(=O)O',
			'methionine' : 'CSCCC(C(=O)O)N',
			'4-methoxybenzaldehyde (anisaldehyde)' : 'COC1=CC=C(C=C1)C=O',
			'methoxychlor' : 'COC1=CC=C(C=C1)C(C2=CC=C(C=C2)OC)C(Cl)(Cl)Cl',
			'methyl acetate' :'CC(=O)OC',
			'methyl cyanoacrylate' : 'COC(=O)C(=C)C#N',
			'methyl isobutyl ketone' : 'CC(C)CC(=O)C',
			'MIBK' : 'CC(C)CC(=O)C',
			'methyl isocyanate' : 'CN=C=O',
			'methyl methacrylate' : 'CC(=C)C(=O)OC',
			'methylal' : 'COCOC',
			'methylamine' : 'CN',
			'methyl chloroformate' : 'COC(=O)Cl',
			'methylcyclohexane' : 'CC1CCCCC1',
			'methylene blue ' : 'CN(C)C1=CC2=C(C=C1)N=C3C=CC(=[N+](C)C)C=C3S2.[Cl-]',
			'methylhydrazine' : 'CNN',
			'methylmercury' : 'C[Hg+]',
			'2-methylpropene' : 'CC(=C)C',
			'Isobutylene' : 'CC(=C)C',
			'N-methylpyrrolidone' : 'CN1CCCC1=O',
			'methyltriethoxysilane' :'CCO[Si](C)(OCC)OCC',
			'methyltrimethoxysilane' :'CO[Si](C)(OC)OC',
			'metoprolol' : 'CC(C)NCC(COC1=CC=C(C=C1)CCOC)O',
			'metronidazole' : 'CC1=NC=C(N1CCO)[N+](=O)[O-]',
			'michlers ketone' : 'CN(C)C1=CC=C(C=C1)C(=O)C2=CC=C(C=C2)N(C)C',
			'milrinone' : 'CC1=C(C=C(C(=O)N1)C#N)C2=CC=NC=C2',
			'monocrotophos' : 'CC(=CC(=O)NC)OP(=O)(OC)OC' ,
			'monosodium glutamate' : 'C(CC(=O)[O-])C(C(=O)O)N.O.[Na+]',
			'mordant red 19' : 'C1=CC2=C(C=C1O)C(=O)C3=C(C2=O)C(=C(C=C3)O)O',
			'morpholine' : 'C1COCCN',
			'murexide' : 'C1(=C(NC(=O)NC1=O)O)N=C2C(=O)NC(=O)NC2=O.N',
			'mustard gas ' : 'C(CCl)SCCCl',
			'myrcene' : 'CC(=CCCC(=C)C=C)C',
			'n-nonadecane' : 'CCCCCCCCCCCCCCCCCCC',
			'n-tetradecylbenzene' : 'CCCCCCCCCCCCCCC1=CC=CC=C1',
			'naphthoquinone' : 'CC1=C(C(=O)C2=CC=CC=C2C1=O)CC=C(C)CCCC(C)CCCC(C)CCCC(C)C',
			'vitamin K' : 'CC1=C(C(=O)C2=CC=CC=C2C1=O)CC=C(C)CCCC(C)CCCC(C)CCCC(C)C',
			'2-naphthylamine' : 'C1=CC=C2C=C(C=CC2=C1)N',
			'neomycin' : 'C1C(C(C(C(C1N)OC2C(C(C(C(O2)CN)O)O)N)OC3C(C(C(O3)CO)OC4C(C(C(C(O4)CN)O)O)N)O)O)N',
			'niflumic acid' : 'C1=CC(=CC(=C1)NC2=C(C=CC=N2)C(=O)O)C(F)(F)F',
			'nile red' : 'CCN(CC)C1=CC2=C(C=C1)N=C3C4=CC=CC=C4C(=O)C=C3O2',
			'nimesulide' : 'CS(=O)(=O)NC1=C(C=C(C=C1)[N+](=O)[O-])OC2=CC=CC=C2',
			'nitrilotriacetic acid' : 'C(C(=O)O)N(CC(=O)O)CC(=O)O',
			'nitrobenzene' : 'C1=CC=C(C=C1)[N+](=O)[O-]',
			'nitrocellulose' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-])CO[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-])OC3C(C(C(C(O3)CO[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-]',
			'nitroethane' : 'CC[N+](=O)[O-]',
			'nitrofen' : 'C1=CC(=CC=C1[N+](=O)[O-])OC2=C(C=C(C=C2)Cl)Cl',
			'nitrofurantoin': 'C1C(=O)NC(=O)N1N=CC2=CC=C(O2)[N+](=O)[O-]',
			'nitroglycerine' : 'C(C(CO[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-]',
			'nitromethane' : 'C[N+](=O)[O-]',
			'nitrosobenzene' : 'C1=CC=C(C=C1)N=O',
			'nitrosomethylurethane' : 'CCOC(=O)N(C)N=O',
			'nominine' : 'CC1CCC(C2(C1(CCC(=C)C2CC3=CNC4=CC=CC=C43)C)CCC=C(C)C)O',
			'nonacosane' : 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
			'noradrenaline' : 'C1=CC(=C(C=C1C(CN)O)O)O',
			'norepinephrine' : 'C1=CC(=C(C=C1C(CN)O)O)O',
			'norephidrine' : 'CC(C(C1=CC=CC=C1)O)N',
			'norcarane' : 'C1CCC2CC2C1',
			'norleucine' : 'CCCCC(C(=O)O)N',
			'nujol' : 'CC(=C)C(=O)OCC(COC1=CC=C(C=C1)C(C)(C)C2=CC=C(C=C2)OCC(COC(=O)C(=C)C)O)O',
			'NMN' : 'C1=CC(=C[N+](=C1)C2C(C(C(O2)COP(=O)([O-])[O-])O)O)C(=O)N',
			'octabromodiphenyl ether' : 'C1=C(C(=C(C(=C1Br)Br)Br)Br)OC2=CC(=C(C(=C2Br)Br)Br)Br',
			'1-octanethiol' : 'CCCCCCCCS',
			'octanoic acid' : 'CCCCCCCC(=O)O',
			'4-octylphenol' :'CCCCCCCCC1=CC=C(C=C1)O',
			'oleic Acid' : 'CCCCCCCCC=CCCCCCCCC(=O)O',
			'orcinol' : 'CC1=CC(=CC(=C1)O)O',
			'ornithine' : 'C(CC(C(=O)O)N)CN',
			'orotic acid' : 'C1=C(NC(=O)NC1=O)C(=O)O',
			'oxalyl chloride ' : 'C(=O)(C(=O)Cl)Cl',
			'oxamide' : 'C(=O)(C(=O)N)N',
			'oxazole' : 'C1=COC=N1',
			'oxolinic acid' : 'CCN1C=C(C(=O)C2=CC3=C(C=C21)OCO3)C(=O)O',
			'oxymetholone' : 'CC12CCC3C(C1CCC2(C)O)CCC4C3(CC(=CO)C(=O)C4)C',
			'quinaldine' : 'CC1=NC2=CC=CC=C2C=C1',
			'quinazoline' : 'C1=CC=C2C(=C1)C=NC=N2',
			'quinhydrone' : 'C1=CC(=O)C=CC1=O.C1=CC(=CC=C1O)O',
			'quinine' : 'COC1=CC2=C(C=CN=C2C=C1)C(C3CC4CCN3CC4C=C)O',
			'quinone' : 'C1=CC(=O)C=CC1=O',
			'raffinose' : 'C(C1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3(C(C(C(O3)CO)O)O)CO)O)O)O)O)O)O)O',
			'resorcinol' : 'C1=CC(=CC(=C1)O)O',
			'rhodanine' : 'C1C(=O)NC(=S)S1',
			'rosolic acid' : 'C1=CC(=O)C=CC1=C(C2=CC=C(C=C2)O)C3=CC=C(C=C3)O',
			'rotenone' : 'CC(=C)C1CC2=C(O1)C=CC3=C2OC4COC5=CC(=C(C=C5C4C3=O)OC)OC',
			'saccharin' : 'C1=CC=C2C(=C1)C(=O)NS2(=O)=O',
			'safrole' : 'C=CCC1=CC2=C(C=C1)OCO2',
			'salicin' : 'C1=CC=C(C(=C1)CO)OC2C(C(C(C(O2)CO)O)O)O',
			'salicylaldehyde' : 'C1=CC=C(C(=C1)C=O)O',
			'salvinorin a' : 'CC(=O)OC1CC(C2(CCC3C(=O)OC(CC3(C2C1=O)C)C4=COC=C4)C)C(=O)OC',
			'sarin' : 'CC(C)OP(=O)(C)F',
			'sclareol' : 'CC1(CCCC2(C1CCC(C2CCC(C)(C=C)O)(C)O)C)C',
			'sebacic acid' : 'C(CCCCC(=O)O)CCCC(=O)O2',
			'sebacoyl chloride' : 'C(CCCCC(=O)Cl)CCCC(=O)Cl',
			'selacholeic acid' : 'CCCCCCCCC=CCCCCCCCCCCCCCC(=O)O',
			'selenocysteine' : 'C(C(C(=O)O)N)[Se]',
			'selenomethionine' : 'C[Se]CCC(C(=O)O)N',
			'serine' : 'C(C(C(=O)O)N)O',
			'serotonin' : 'C1=CC2=C(C=C1O)C(=CN2)CCN',
			'sildenafil' : 'CCCC1=NN(C2=C1NC(=NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C',
			'viagra' : 'CCCC1=NN(C2=C1NC(=NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C',
			'shikimic acid' : 'C1C(C(C(C=C1C(=O)O)O)O)O',
			'skatole' : 'CC1=CNC2=CC=CC=C12',
			'sorbic acid' : 'CC=CC=CC(=O)O',
			'sotolone' : 'CC1C(=C(C(=O)O1)O)C',
			'spermidine' : 'C(CCNCCCN)CN',
			'strychnine' : 'C1CN2CC3=CCOC4CC(=O)N5C6C4C3CC2C61C7=CC=CC=C75',
			'styrene': 'C=CC1=CC=CC=C1',
			'succinic anhydride' : 'C1CC(=O)OC1=O',
			'sulfanilamide' : 'C1=CC(=CC=C1N)S(=O)(=O)N',
			'sulfanilic acid' : 'C1=CC(=CC=C1N)S(=O)(=O)O',
			'sulforhodamine b' : 'CCN(CC)C1=CC2=C(C=C1)C(=C3C=CC(=[N+](CC)CC)C=C3O2)C4=C(C=C(C=C4)S(=O)(=O)O)S(=O)(=O)[O-]',
			'suxamethonium chloride' : 'C[N+](C)(C)CCOC(=O)CCC(=O)OCC[N+](C)(C)C.Cl.Cl',
			'xanthan gum' : 'C1C2=CC=CC=C2OC3=CC=CC=C31',
			'xanthone' : 'C1=CC=C2C(=C1)C(=O)C3=CC=CC=C3O2',
			'xylenol orange' : 'CC1=C(C(=CC(=C1)C2(C3=CC=CC=C3S(=O)(=O)O2)C4=CC(=C(C(=C4)CN(CC(=O)O)CC(=O)O)O)C)CN(CC(=O)O)CC(=O)O)O',
			'xylose' : 'C(C(C(C(C=O)O)O)O)O',
			'yohimbine hydrochloride' : 'COC(=O)C1C(CCC2C1CC3C4=C(CCN3C2)C5=CC=CC=C5N4)O.Cl',
			'yohimbinic acid monohydrate' : 'C1CC(C(C2C1CN3CCC4=C(C3C2)NC5=CC=CC=C45)C(=O)O)O.O',
			'zingiberene' : 'CC1=CCC(C=C1)C(C)CCC=C(C)C',
			'umbelliferone' : 'C1=CC(=CC2=C1C=CC(=O)O2)O',
			'undecanol' : 'CCCCCCCCCCCO',
			'uracil' : 'C1=CNC(=O)NC1=O',
			'urethane' : 'CCOC(=O)N',
			'uric acid' : 'C12=C(NC(=O)N1)NC(=O)NC2=O',
			'uridine' : 'C1=CN(C(=O)NC1=O)C2C(C(C(O2)CO)O)O',
			'usnic acid' : 'CC1=C(C(=C2C(=C1O)C3(C(=CC(=O)C(C3=O)C(=O)C)O2)C)C(=O)C)O',
			'valine' : 'CC(C)[C@@H](C(=O)O)N',
			'diazepam' : 'CN1C2=C(C(C3=CC=CC=C3)=NCC1=O)C=C(Cl)C=C2',
			'valium' : 'CN1C2=C(C(C3=CC=CC=C3)=NCC1=O)C=C(Cl)C=C2',
			'valproate' : 'O=C(O)C(CCC)CCC',
			'vanillin' : 'c1(C=O)cc(OC)c(O)cc1',
			'venlafaxine' : 'OC2(C(c1ccc(OC)cc1)CN(C)C)CCCCC2',
			'vinyl acetate' : 'C=COC(C)=O',
			'vinyl fluoride' : 'FC=C',
			'1-1-dichloroethene' : 'ClC(Cl)=C',
			'vitamin A' : 'OC/C=C(C)/C=C/C=C(C)/C=C/C1=C(C)/CCCC1(C)C',
			'retinol' : 'OC/C=C(C)/C=C/C=C(C)/C=C/C1=C(C)/CCCC1(C)C',
			'thiamine' : 'Cc1c(sc[n+]1Cc2cnc([nH]c2=N)C)CCO',
			'vitamin B1' : 'Cc1c(sc[n+]1Cc2cnc([nH]c2=N)C)CCO',
			'riboflavin' : 'c12cc(C)c(C)cc1N=C3C(=O)NC(=O)N=C3N2C[C@H](O)[C@H](O)[C@H](O)CO',
			'vitamin B2' : 'c12cc(C)c(C)cc1N=C3C(=O)NC(=O)N=C3N2C[C@H](O)[C@H](O)[C@H](O)CO',
			'niacin' : 'OC(=O)c1cccnc1',
			'nicotinic acid' : 'OC(=O)c1cccnc1',
			'adenine' : 'NC1=NC=NC2=C1N=C[NH]2',
			'pantothenic acid' : 'CC(C)(CO)C(C(=O)NCCC(=O)O)O',
			'vitamin B5' : 'CC(C)(CO)C(C(=O)NCCC(=O)O)O',
			'pyridoxine' : 'OCc1cnc(C)c(O)c1CO',
			'vitamin B6' : 'OCc1cnc(C)c(O)c1CO',
			'pyridoxol' : 'OCc1cnc(C)c(O)c1CO',
			'tropane': 'N1(C)[C@H]2CC[C@@H]1CCC2',
			'tyrosine' : 'N[C@@H](Cc1ccc(O)cc1)C(O)=O',
			'trytophan' : 'c1ccc2c(c1)c(c[nH]2)C[C@@H](C(=O)O)N',
			'tropinone' : 'CN1[C@@H]2CC[C@H]1CC(=O)C2',
			'triphenylphospine' : 'c3c(P(c1ccccc1)c2ccccc2)cccc3',
			'triphenylphosphane' : 'c3c(P(c1ccccc1)c2ccccc2)cccc3',
			'trinitrotoluene' : 'Cc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
			'TNT' : 'Cc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
			'triphenylmethanol' : 'OC(c1ccccc1)(c2ccccc2)c3ccccc3',
			'triphenylcarbinol' : 'OC(c1ccccc1)(c2ccccc2)c3ccccc3',
			'triphenyl methane' : 'c1c(cccc1)C(c2ccccc2)c3ccccc3',
			'triphenylene' : 'C1(C=CC=C3)=C3C(C=CC=C4)=C4C2=C1C=CC=C2',
			'triphenylstibine' : 'c3c([Sb](c1ccccc1)c2ccccc2)cccc3',
			'triphenylamine' : 'c3c(N(c1ccccc1)c2ccccc2)cccc3',
			'triphenyl phosphate' : 'O=P(Oc1ccccc1)(Oc2ccccc2)Oc3ccccc3',
			'2,2,4-trimethylpentane' : 'CC(C)CC(C)(C)C',
			'isooctane' : 'CC(C)CC(C)(C)C',
			'1,2,3-trimethylbenzene' : 'c1(cccc(c1C)C)C',
			'hemellitol' : 'c1(cccc(c1C)C)C',
			'1,2,4-trimethylbenzene' : 'c1c(ccc(c1C)C)C',
			'pseudocumene' : 'c1c(ccc(c1C)C)C',
			'1,3,5-trimethylbenzene' : 'Cc1cc(cc(c1)C)C',
			'mesitylene' : 'Cc1cc(cc(c1)C)C',
			'trimethylamine' : 'CN(C)C',
			'Trimethyl phosphite' : 'O(P(OC)OC)C',
			'1-(3,4,5-Trimethoxyphenyl)propan-2-amine' : 'NC(C)CC1=CC(OC)=C(OC)C(OC)=C1',
			'3,4,5-trimethoxyamphetamine' : 'NC(C)CC1=CC(OC)=C(OC)C(OC)=C1',
			'1-(2,4,5-Trimethoxyphenyl)propan-2-amine' : 'NC(C)CC1=CC(OC)=CC(OC)=C1OC',
			'2,4,5-trimethoxyamphetamine' : 'NC(C)CC1=CC(OC)=CC(OC)=C1OC',
			'1-(2,3,4-Trimethoxyphenyl)propan-2-amine,' : 'NC(C)CC1=CC=C(OC)C(OC)=C1OC',
			'2,3,4-trimethoxyamphetamine' : 'NC(C)CC1=CC=C(OC)C(OC)=C1OC',
			'1-(2,3,5-Trimethoxyphenyl)propan-2-amine' : 'NC(C)CC1=CC(OC)=CC(OC)=C1OC',
			'2,3,5-trimethoxyamphetamine' : 'NC(C)CC1=CC(OC)=CC(OC)=C1OC',
			'1-(2,3,6-Trimethoxyphenyl)propan-2-amine' : 'NC(C)CC1=C(OC)C=CC(OC)=C1OC',
			'2,3,6-trimethoxyamphetamine' : 'NC(C)CC1=C(OC)C=CC(OC)=C1OC',
			'1-(2,4,6-Trimethoxyphenyl)propan-2-amine' : 'NC(C)CC1=C(OC)C=C(OC)C=C1OC',
			'2,4,6-trimethoxyamphetamine' : 'NC(C)CC1=C(OC)C=C(OC)C=C1OC',
			'fluoroform' : 'FC(F)F',
			'2,2,2-trifluoroethanol' : 'OCC(F)(F)F',
			'trifluoroacetic acid' : 'FC(F)(F)C(=O)O',
			'DABCO' : 'C1CN2CCN1CC2',
			'1,4-diazabicyclo[2.2.2]octane' : 'C1CN2CCN1CC2',
			'triethylene glycol' : 'OCCOCCOCCO',
			'triethylamine' : 'CCN(CC)CC',
			'1,1,1-trifluoroethane' : 'FC(F)(F)C',
			'triethylaluminium' : 'CC[Al](CC)CC',
			'TEAL' : 'CC[Al](CC)CC',
			'tridecanoic acid' : 'O=C(O)CCCCCCCCCCCC',
			'tridecylic acid' : 'O=C(O)CCCCCCCCCCCC',
			'tridecane' : 'CCCCCCCCCCCCC',
			'triclosan' : 'Clc2cc(Cl)ccc2Oc1ccc(Cl)cc1O',
			'triclabendazole' : 'Clc3cccc(Oc2c(Cl)cc1c(nc(SC)n1)c2)c3Cl',
			'tricine' : 'OCC(CO)(CO)NCc(:[o]):[oH]',
			'2,4,6-trichlorophenol' : 'OC1=C(C=C(C=C1Cl)Cl)Cl',
			'tromethamine' : 'OCC(N)(CO)CO',
			'tris' : 'OCC(N)(CO)CO',
			'trichlorofluoromethane' : 'C(F)(Cl)(Cl)Cl',
			'freon-11' : 'C(F)(Cl)(Cl)Cl',
			'trichloroethylene' : 'Cl\C=C(/Cl)Cl',
			'trichloroacetonitrile' : 'ClC(Cl)(Cl)C#N',
			'1,1,1-trichloroethane' : 'ClC(Cl)(Cl)C',
			'trichloroacetic acid' : 'ClC(Cl)(Cl)C(O)=O',
			'tributylphosphine' : 'CCCCP(CCCC)CCCC',
			'tributylamine' : 'N(CCCC)(CCCC)CCCC',
			'thymine' : 'Cc1c[nH]c(=O)[nH]c1=O',
			'thymidine' : 'Cc1cn(c(=O)[nH]c1=O)[C@H]2C[C@@H]([C@H](O2)CO)O',
			'eltrombopag' : 'CC1=C(C=C(C=C1)N2C(=O)C(=C(N2)C)NN=C3C=CC=C(C3=O)C4=CC(=CC=C4)C(=O)O)C',
			'threonine' : 'C[C@H]([C@@H](C(=O)O)N)O',
			'thorin' : '[Na+].[Na+].O[As](O)(=O)C1=CC=CC=C1NN=C1C(=O)C(=CC2=C1C=CC(=C2)S([O-])(=O)=O)S([O-])(=O)=O',
			'thiram' : 'CN(C)C(=S)SSC(=S)N(C)C',
			'ambroxol' : 'NC1=C(Br)C=C(Br)C=C1CN[C@H]1CC[C@H](O)CC1',
			'thiourea' : 'C(=S)(N)N',
			'tiglic acid' : 'O=C(O)/C(=C/C)C',
			'thymolphthalein' : 'O=C1OC(c2ccccc12)(c3cc(c(O)cc3C)C(C)C)c4cc(c(O)cc4C)C(C)C',
			'thymol' : 'CC(C)c1ccc(C)cc1O',
			'demeton-O' : 'CCOP(=S)(OCC)OCCSCC',
			'tetryl' : 'CN(c1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]',
			'thalidomide' : 'O=C(N1C2CCC(NC2=O)=O)C3=CC=CC=C3C1=O',
			'thiazole' : 'n1ccsc1',
			'thioacetamide' : 'S=C(N)C',
			'thiolactic acid' : 'SC(C)C(O)=O',
			'thiophene' : 'c1ccsc1',
			'thiofuran' : 'c1ccsc1',
			'thiophosgene' : 'ClC(Cl)=S',
			'tetralin' : 'c1ccc2c(c1)CCCC2',
			'tetramethrin' : 'O=C1\C3=C(/C(=O)N1COC(=O)C2C(\C=C(/C)C)C2(C)C)CCCC3',
			'tetramethylsilane' : 'C[Si](C)(C)C',
			'tetramethylurea' : 'CN(C)C(=O)N(C)C',
			'tetranitromethane' : 'C([N+](=O)[O-])([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]',
			'tetrathiafulvalene' : 'C1=CSC(=C2SC=CS2)S1',
			'tetrodotoxin' : 'O1[C@@H]4[C@@](O)([C@@H]3O[C@@]1(O)[C@@H](O)[C@]2(N\C(=N/[C@H](O)[C@H]23)N)[C@@H]4O)CO',
			'tetrahydrofuran' : 'C1CCOC1',
			'oxolane' : 'C1CCOC1',
			'tetrahedrane' : 'C12C3C1C23',
			'tetrafluoroethylene' : 'FC(F)=C(F)F',
			'tetradecane' : 'CCCCCCCCCCCCCC',
			'carbon tetrachloride' : 'ClC(Cl)(Cl)Cl',
			'tetrachloroethylene' : 'Cl/C(Cl)=C(/Cl)Cl',
			'tartrazine' : '[Na+].[Na+].[Na+].[O-]S(=O)(=O)c1ccc(cc1)/N=N/c3c(nn(c2ccc(cc2)S([O-])(=O)=O)c3O)C([O-])=O',
			'succinic anhydride' : 'O=C1OC(=O)CC1',
			'styrene' : 'c1ccccc1C=C',
			'vinylbenzene' : 'c1ccccc1C=C',
			'strychnine' : 'O=C7N2c1ccccc1[C@@]64[C@@H]2[C@@H]3[C@@H](OC/C=C5\[C@@H]3C[C@@H]6N(CC4)C5)C7',
			'stearic acid' : 'CCCCCCCCCCCCCCCCCC(=O)O',
			'squalene' : 'CC(=CCC/C(=C/CC/C(=C/CC/C=C(/CC/C=C(/CCC=C(C)C)\C)\C)/C)/C)C',
			'Suxamethonium chloride' : '[Cl-].[Cl-].O=C(OCC[N+](C)(C)C)CCC(=O)OCC[N+](C)(C)C',
			'succinylcholine' : '[Cl-].[Cl-].O=C(OCC[N+](C)(C)C)CCC(=O)OCC[N+](C)(C)C',
			'suxamethonium' : '[Cl-].[Cl-].O=C(OCC[N+](C)(C)C)CCC(=O)OCC[N+](C)(C)C',
			'sulfanilic acid' : 'C1=CC(=CC=C1N)S(=O)(=O)O',
			'L-fructose' : 'C(C(C(C(C(=O)CO)O)O)O)O',
			'ribose' : 'C([C@H]([C@H]([C@H](C=O)O)O)O)O',
			'quinoxaline' : 'c1cccc2nccnc12',
			'propionitrile' : 'CCC#N',
			'pyrrolidine' : 'C1CCNC1',
			'pyrrole' : 'N1C=CC=C1',
			'Pyroglutamic acid' : 'O=C(O)[C@H]1NC(=O)CC1',
			'pyroglutamate' : 'O=C(O)[C@H]1NC(=O)CC1',
			'pyrimidine ' : 'c1cncnc1',
			'pyrimethamine' : 'Clc2ccc(c1c(nc(nc1CC)N)N)cc2',
			'mepyramine' : 'O(c1ccc(cc1)CN(c2ncccc2)CCN(C)C)C',
			'pyrilamine' : 'O(c1ccc(cc1)CN(c2ncccc2)CCN(C)C)C',
			'2-Pyridone' : 'C1=CC=CNC(=O)1',
			'pyridazine' : 'c1ccnnc1',
			'pyrazole' : 'n1cccn1',
			'pyrazine' : 'c1cnccn1',
			'putrescine' : 'NCCCCN',
			'tetramethylenediamine' : 'NCCCCN',
			'purine' : 'c1c2c(nc[nH]2)ncn1',
			'1,8-bis(dimethylamino)naphthalene' : 'CN(C)C1=CC=CC2=C1C(=CC=C2)N(C)C',
			'propoxur' : 'CC(C)Oc1ccccc1OC(=O)NC',
			'baygon' : 'CC(C)Oc1ccccc1OC(=O)NC',
			'propionaldehyde' : 'CCC=O',
			'propanal' : 'CCC=O',
			'propiolic acid' : 'C#CC(=O)O',
			'propiconazole' : 'Clc1ccc(c(Cl)c1)C2(OCC(O2)CCC)Cn3ncnc3',
			'propargyl alcohol' : 'C#CCO',
			'propionic acid' : 'CCC(=O)O',
			'proline' : 'C1CC(NC1)C(=O)O',
			'procaine' : 'O=C(OCCN(CC)CC)c1ccc(N)cc1',
			'primaquine' : 'O(c1cc(NC(C)CCCN)c2ncccc2c1)C',
			'prednisone' : 'O=C(CO)[C@@]3(O)CC[C@H]2[C@@H]4CC\C1=C\C(=O)\C=C/[C@]1(C)[C@H]4C(=O)C[C@@]23C',
			'potassium 2-ethylhexanoate' : '[K+].[O-]C(=O)C(CC)CCCC',
			'clavulanic acid' : 'O=C2N1[C@H](C(/O[C@@H]1C2)=C/CO)C(=O)O',
			'polyvinylpyrrolidone' : 'N1(C(CCC1)=O)[C@@H](C*)*',
			'polyvidone' : 'N1(C(CCC1)=O)[C@@H](C*)*',
			'povidone' : 'N1(C(CCC1)=O)[C@@H](C*)*',
			'polyvinyl acetate' : 'O([C@@H](C*)*)C(C)=O',
			'piperylene' : 'C/C=C/C=C',
			'piperonal' : 'c1cc2c(cc1C=O)OCO2',
			'heliotropin' : 'c1cc2c(cc1C=O)OCO2',
			'piperidine' : 'C1CCNCC1',
			'piperazine' : 'C1CNCCN1',
			'pinacol' : 'CC(C)(O)C(C)(C)O',
			'pimelic acid' : 'OC(=O)CCCCCC(=O)O',
			'picric acid' : 'O=[N+]([O-])c1cc(cc([N+]([O-])=O)c1O)[N+]([O-])=O',
			'phytic acid' : '[C@@H]1([C@@H]([C@@H]([C@@H]([C@H]([C@@H]1OP(=O)(O)O)OP(=O)(O)O)OP(=O)(O)O)OP(=O)(O)O)OP(=O)(O)O)OP(=O)(O)O',
			'phthalic acid' : 'C1=CC=C(C(=C1)C(=O)O)C(=O)O',
			'phthalic anhydride' : 'O=c1oc(=O)c2ccccc12',
			'phloroglucinol' : 'c1c(cc(cc1O)O)O',
			'phenylthiocarbamide' : 'C1=CC=C(C=C1)NC(=S)N',
			'phenylthiourea' :  'C1=CC=C(C=C1)NC(=S)N',
			'phorate' : 'S=P(OCC)(SCSCC)OCC',
			'phenol red' : 'O=S2(=O)OC(c1ccccc12)(c3ccc(O)cc3)c4ccc(O)cc4',
			'phenolsulfonphthalein' : 'O=S2(=O)OC(c1ccccc12)(c3ccc(O)cc3)c4ccc(O)cc4',
			'phenobarbital' : 'O=C1NC(=O)NC(=O)C1(c2ccccc2)CC',
			'phenethylamine' : 'c1ccc(cc1)CCN',
			'phencyclidine' : 'C1(C2(N3CCCCC3)CCCCC2)=CC=CC=C1',
			'phenanthrene' : 'c1ccc2c3ccccc3ccc2c1',
			'phenacyl bromide' : 'O=C(c1ccccc1)CBr',
			'phenacetin' : 'O=C(Nc1ccc(OCC)cc1)C',
			'perylene' : 'c1ccc5cccc4c5c1c2cccc3cccc4c23',
			'peracetic acid' : 'CC(=O)OO',
			'peroxyacetic acid' : 'CC(=O)OO',
			'permethrin' : 'Cl/C(Cl)=C/C3C(C(=O)OCc2cccc(Oc1ccccc1)c2)C3(C)C',
			'perfluorotributylamine' : 'C(C(C(F)(F)F)(F)F)(C(N(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F',
			'FC43' : 'C(C(C(F)(F)F)(F)F)(C(N(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F',
			'pentetic acid' : 'C(CN(CC(=O)O)CC(=O)O)N(CCN(CC(=O)O)CC(=O)O)CC(=O)O',
			'diethylenetriaminepentaacetic acid' : 'C(CN(CC(=O)O)CC(=O)O)N(CCN(CC(=O)O)CC(=O)O)CC(=O)O',
			'4-Phenyl-4-(1-piperidinyl)cyclohexanol' : 'OC1CCC(N2CCCCC2)(C3=CC=CC=C3)CC1',
			'phenyllithium' : '[Li]c1ccccc1',
			'phenothiazine' : 'c1ccc2c(c1)Nc3ccccc3S2',
			'phenylhydroxylamine' : 'ONC1=CC=CC=C1',
			'phenylhydrazine' : 'NNc1ccccc1',
			'p-phenylenediamine' : 'Nc1ccc(N)cc1',
			'phenylacetylene' : 'C#Cc1ccccc1',
			'phenylacetic acid' : 'O=C(O)Cc1ccccc1',
			'pentabromodiphenyl ether' : 'c1cc(c(cc1Br)Br)Oc2cc(c(cc2Br)Br)Br',
			'pentaerythritol' : 'OCC(CO)(CO)CO',
			'pentadecane' : 'CCCCCCCCCCCCCCC',
			'pentachlorophenol' : 'Oc1c(Cl)c(Cl)c(Cl)c(Cl)c1Cl',
			'pentabromodiphenyl ether' : 'c1cc(c(cc1Br)Br)Oc2cc(c(cc2Br)Br)Br',
			'nonanoic acid' : 'CCCCCCCCC(=O)O',
			'pelargonic acid' : 'CCCCCCCCC(=O)O',
			'parathion' : 'S=P(Oc1ccc(cc1)[N+]([O-])=O)(OCC)OCC',
			'chloroxylenol' : 'CC1=CC(O)=CC(C)=C1Cl',
			'para red' : 'O=N(=O)c1ccc(cc1)/N=N/c2c3ccccc3ccc2O',
			'paranitraniline red' : 'O=N(=O)c1ccc(cc1)/N=N/c2c3ccccc3ccc2O',
			'palmitic acid' : 'CCCCCCCCCCCCCCCC(=O)O',
			'paclitaxel' : 'CC1=C2[C@@]([C@]([C@H]([C@@H]3[C@]4([C@H](OC4)C[C@@H]([C@]3(C(=O)[C@@H]2OC(=O)C)C)O)OC(=O)C)OC(=O)c5ccccc5)(C[C@@H]1OC(=O)[C@H](O)[C@@H](NC(=O)c6ccccc6)c7ccccc7)O)(C)C',
			'4-aminobenzoic acid' : 'O=C(O)c1ccc(N)cc1',
			'PABA ' : 'O=C(O)c1ccc(N)cc1',
			'DNA' : 'c1ccc2c(c1)c(cc(c2O)C(=O)O)O',
			'deoxyribonucleicacid' : 'c1ccc2c(c1)c(cc(c2O)C(=O)O)O',
			'insulin' : 'CCC(C)C(C(=O)NC(C(C)C)C(=O)NC(CCC(=O)O)C(=O)NC(CCC(=O)N)C(=O)NC(CS)C(=O)NC(CS)C(=O)NC(C(C)O)C(=O)NC(CO)C(=O)NC(C(C)CC)C(=O)NC(CS)C(=O)NC(CO)C(=O)NC(CC(C)C)C(=O)NC(CC1=CC=C(C=C1)O)C(=O)NC(CCC(=O)N)C(=O)NC(CC(C)C)C(=O)NC(CCC(=O)O)C(=O)NC(CC(=O)N)C(=O)NC(CC2=CC=C(C=C2)O)C(=O)NC(CS)C(=O)NC(CC(=O)N)C(=O)O)NC(=O)CN.CC(C)CC(C(=O)NC(CC1=CC=C(C=C1)O)C(=O)NC(CC(C)C)C(=O)NC(C(C)C)C(=O)NC(CS)C(=O)NCC(=O)NC(CCC(=O)O)C(=O)NC(CCCNC(=N)N)C(=O)NCC(=O)NC(CC2=CC=CC=C2)C(=O)NC(CC3=CC=CC=C3)C(=O)NC(CC4=CC=C(C=C4)O)C(=O)NC(C(C)O)C(=O)NC(CCCCN)C(=O)N5CCCC5C(=O)NC(C(C)O)C(=O)O)NC(=O)C(C)NC(=O)C(CCC(=O)O)NC(=O)C(C(C)C)NC(=O)C(CC(C)C)NC(=O)C(CC6=CN=CN6)NC(=O)C(CO)NC(=O)CNC(=O)C(CS)NC(=O)C(CC(C)C)NC(=O)C(CC7=CN=CN7)NC(=O)C(CCC(=O)N)NC(=O)C(CC(=O)N)NC(=O)C(C(C)C)NC(=O)C(CC8=CC=CC=C8)N',
			'amoxicillin' : 'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C',
			'loratadine' : 'CCOC(=O)N1CCC(=C2C3=C(CCC4=C2N=CC=C4)C=C(C=C3)Cl)CC1',
			'penicillin G' : 'CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C',
			'L-asparagine' : 'C(C(C(=O)O)N)C(=O)N',
			'azoxybenzene' : 'C1=CC=C(C=C1)N=[N+](C2=CC=CC=C2)[O-]',
			'butanamide' : 'CCCC(=O)NC1=CC=CC=C1',
			'butyranilide' : 'CCCC(=O)NC1=CC=CC=C1',
			'chloropicrin' : 'C([N+](=O)[O-])(Cl)(Cl)Cl',
			'caffeic acid' : 'C1=CC(=C(C=C1C=CC(=O)O)O)O',
			'cellosolve' : 'CCOCCO',
			'cellulose gel' : 'COC1C(OC(C(C1O)O)OC2C(OC(C(C2O)O)OC)CO)CO',
			'benzofuran' : 'o2c1ccccc1cc2',
			'creatine' : 'CN(CC(O)=O)C(N)=N',
			'cellulose' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
			'DEAE-cellulose' : 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
			'diethanolamine' : 'C(CO)NCCO',
			'durene' : 'c1c(c(cc(c1C)C)C)C',
			'fluorescein' : 'c1ccc2c(c1)C(=O)OC23c4ccc(cc4Oc5c3ccc(c5)O)O',
			'myoinositol' : '[H]O[C@@]1([H])[C@]([H])(O[H])[C@@]([H])(O[H])[C@]([H])(O[H])[C@]([H])(O[H])[C@]1([H])O[H]',
			'diglycerol' : 'C(C(COCC(CO)O)O)O',
			'tetradecanoic acid' : 'CCCCCCCCCCCCCC(=O)O',
			'myristic acid' : 'CCCCCCCCCCCCCC(=O)O',
			'phlorogucinol' : 'C1=C(C=C(C=C1O)O)O',
			'hippuric acid' : 'C1=CC=C(C=C1)C(=O)NCC(=O)O',
			'ionone' : 'O=C(\C=C\C1\C(=C)CCCC1(C)C)C',
			'oxalic acid' : 'C(=O)(C(=O)O)O',
			'succinic acid' : 'C(CC(=O)O)C(=O)O',
			'asuccin' : 'C(CC(=O)O)C(=O)O',
			'starch' : 'CC1C(C(C(C(O1)CO)OC2C(C(C(C(O2)COC3C(C(C(C(O3)CO)OC)O)O)OC4C(C(C(C(O4)CO)OC)O)OC(=O)C)O)O)O)O',
			'cornstarch' : 'CC1C(C(C(C(O1)CO)OC2C(C(C(C(O2)COC3C(C(C(C(O3)CO)OC)O)O)OC4C(C(C(C(O4)CO)OC)O)O)O)O)O)O',
			'amylum' : 'CC1C(C(C(C(O1)CO)OC2C(C(C(C(O2)COC3C(C(C(C(O3)CO)OC)O)O)OC4C(C(C(C(O4)CO)OC)O)O)O)O)O)O',
			'hydroxyethyl starch' : 'C(COCC1C(C(C(C(O1)OCCO)OCCO)OCCO)OCCO)O.C(C1C(C(C(C(O1)O)O)O)O)O',
			'adenosine triphosphate' : 'O=P(O)(O)OP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n2cnc1c(ncnc12)N)[C@H](O)[C@@H]3O',
			'ATP' : 'O=P(O)(O)OP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n2cnc1c(ncnc12)N)[C@H](O)[C@@H]3O',
			'theobromine' : 'CN1C=NC2=C1C(=O)NC(=O)N2C',
			'theosalvose' : 'CN1C=NC2=C1C(=O)NC(=O)N2C',
			'adenosine diphosphate' : 'O=P(O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n2cnc1c(ncnc12)N)[C@H](O)[C@@H]3',
			'ADP' : 'O=P(O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n2cnc1c(ncnc12)N)[C@H](O)[C@@H]3O',
			'salicin' : 'C1=CC=C(C(=C1)CO)OC2C(C(C(C(O2)CO)O)O)O',
			'phorone' : 'O=C(C=C(C)C)C=C(C)C',
			'phthalimide' : 'C1=CC=C2C(=C1)C(=O)NC2=O',
			'ethoxybenzene' : 'CCOC1=CC=CC=C1',
			'phenetole' : 'CCOC1=CC=CC=C1',
			'nicotine' : 'CN1CCCC1C2=CN=CC=C2',
			'L-nicotine' : 'CN1CCCC1C2=CN=CC=C2',
			'morphine' : 'CN1CCC23C4C1CC5=C2C(=C(C=C5)O)OC3C(C=C4)O',
			'L-menthol' : 'CC1CCC(C(C1)O)C(C)C',
			'levomenthol' : 'CC1CCC(C(C1)O)C(C)C',
			'menthol' : 'CC1CCC(C(C1)O)C(C)C',
			'Dl-menthol' : 'CC1CCC(C(C1)O)C(C)C',
			'leucine' : 'CC(C)C[C@@H](C(=O)O)N',
			'lepidine' : 'CC1=CC=NC2=CC=CC=C12',
			'quinoline' : 'CC1=CC=NC2=CC=CC=C12',
			'laurone' : 'CCCCCCCCCCCC(=O)CCCCCCCCCCC',
			'lactic anhydride' : 'CC(C(=O)OC(=O)C(C)O)O',
			'koch acid' : 'C1=C2C=C(C=C(C2=C(C=C1S(=O)(=O)O)N)S(=O)(=O)O)S(=O)(=O)O',
			'iodoform' : 'C(I)(I)I',
			'triiodomethane' : 'C(I)(I)I',
			'indoxyl sulfate' : 'C1=CC=C2C(=C1)C(=CN2)OS(=O)(=O)O',
			'indoxylsulfuric acid' : 'C1=CC=C2C(=C1)C(=CN2)OS(=O)(=O)O',
			'ethylene glycol diacetate' : 'CC(=O)OCCOC(=O)C',
			'glycol diacetate' : 'CC(=O)OCCOC(=O)C',
			'glycine' : 'C(C(=O)O)N',
			'glucuronic acid' : 'O=C(O)[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O',
			'galactose' : 'O[C@H]1[C@@H](O)[C@H](O[C@H](O)[C@@H]1O)CO',
			'carbol fuchsin' : 'CC1=CC(=C(C2=CC=C(C=C2)N)C3=CC=C(C=C3)N)C=CC1=N.C1=CC=C(C=C1)O.Cl',
			'ethyl benzoate' : 'CCOC(=O)C1=CC=CC=C1',
			'ethyl azidoacetate' : 'CCOC(=O)CN=[N+]=[N-]',
			'acetic acid' : 'CCOC(=O)CN=[N+]=[N-]',
			'eosin Y' : 'O=C5C(Br)=C2O C1=C(Br)C([O-]) =C(Br)C=C1C(C4=C (C([O-])=O)C=C C=C4)=C2C=C3Br',
			'eosin B' : 'O=C5C(Br)=C2O C1=C(Br)C([O-]) =C([N+]([O-])=O) C=C1C(C4=C(C([O-]) =O)C=CC=C4)=C2 C=C3[N+]([O-])=O',
			'docosane' : 'CCCCCCCCCCCCCCCCCCCCCC',
			'ethyl caproate' : 'CCCCCC(=O)OCC',
			'1,4-dioxane' : 'O1CCOCC1',
			'cantharidin' : 'O=C2OC([C@@]1(C)[C@@H]3CC[C@@H](O3)[C@]12C)=O',
			'carbazole' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N2',
			'chlorobutanol' : 'ClC(Cl)(Cl)C(C)(C)O',
			'chloropyhll' : 'CCC1=C(C2=NC1=CC3=C(C4=C(C(C(=C4[N-]3)C5=NC(=CC6=NC(=C2)C(=C6C)C=C)C(C5CCC(=O)OCC=C(C)CCCC(C)CCCC(C)CCCC(C)C)C)C(=O)OC)[O-])C)C.[Mg+2]',
			'P-cymene' : 'CC1=CC=C(C=C1)C(C)C',
			'dolcymene' : 'CC1=CC=C(C=C1)C(C)C',
			'decalin' : 'C1CCC2CCCCC2C1',
			'decahydronaphthalene' : 'C1CCC2CCCCC2C1',
			'dibenzoylmethane' : 'C1=CC=C(C=C1)C(=O)CC(=O)C2=CC=CC=C2',
			'diethylene glycol dinitrate' : 'C(CO[N+](=O)[O-])OCCO[N+](=O)[O-]',
			'coniine' : 'CCCC1CCCCN1',
			'lindane' : 'Cl[C@H]1[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H]1Cl',
			'basketane' : 'C2CC5C1C4C3C1C2C3C45',
			'cubane' : 'C12C3C4C1C5C2C3C45',
			'olympicene' : 'C1C=C2C=CC3=C4C2=C5C1=CC=CC5=CC4=CC=C3',
			'penguinone' : 'CC1=CC(=O)C=C(C1(C)C)C',
			'prismane' : 'C12C3C1C4C2C34',
			'quadratic acid' : 'c1(c(c(=O)c1=O)O)O',
			'sulflower' : 'c12c3c4c5c6c7c8c1c9sc2sc3sc4sc5sc6sc7sc8s9',
			'fullerene' : 'C12=C3C4=C5C6=C1C7=C8C9=C1C%10=C%11C(=C29)C3=C2C3=C4C4=C5C5=C9C6=C7C6=C7C8=C1C1=C8C%10=C%10C%11=C2C2=C3C3=C4C4=C5C5=C%11C%12=C(C6=C95)C7=C1C1=C%12C5=C%11C4=C3C3=C5C(=C81)C%10=C23',
			'bullvalene' : 'C\2=C\C/1\C=C/C3C(\C=C\1)C/23',
			'arsole' : '[AsH]1C=CC=C1',
			'megaphone' : 'O=C1C=C[C@H](OC)C[C@]1(CC=C)[C@H](C)[C@@H](O)C2=CC(OC)=C(OC)C(OC)=C2',
			'rhamnetin' : 'COC1=CC(=C2C(=C1)OC(=C(C2=O)O)C3=CC(=C(C=C3)O)O)O',
			'deoxyuridylic acid' : 'O=P(O)(O)OC[C@H]2O[C@@H](N\1C(=O)NC(=O)/C=C/1)C[C@@H]2O',
			'uranocene' : '[cH-]/1/cc\cc/[cH-]/cc1.[cH-]/1/cc\cc/[cH-]/cc1.[U]',
			'vomitoxin' : 'O=C4\C(=C/[C@H]3O[C@H]2[C@]1(OC1)[C@](C[C@H]2O)([C@@]3(CO)[C@@H]4O)C)C',
			'montelukast' : 'O=C(O)CC1(CC1)CS[C@@H](c2cccc(c2)\C=C\c3nc4cc(Cl)ccc4cc3)CCc5ccccc5C(O)(C)C',
			'acetic acid anhydride' : 'CC(=O)OC(=O)C',
			'sylic acid' : 'C1=CC=C(C(=C1)C(=O)O)O',
			'abietinic acid' : 'CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C',
			'acetaldehyde diethylacetal' : 'CCOC(C)OCC',
			'ethanol' : 'CCO',
			'paraldehyde' : 'CC1OC(OC(O1)C)C',
			'ethanamide' : 'CC(=O)N',
			'antifebrin' : 'CC(=O)NC1=CC=CC=C1',
			'o-ethoxyacetanalide' : 'CCOC1=CC=C(C=C1)NC(=O)C',
			'N-tolylacetamide' : 'CC1=CC=CC=C1NC(=O)C',
			'ethanoic acid' : 'CC(=O)O',
			'vinegar acid' : 'CC(=O)O',
			'acetyl oxide' : 'CC(=O)OC(=O)C',
			'acetic oxide' : 'CC(=O)OC(=O)C',
			'methyl cyanide' : 'CC#N',
			'propanone' : 'CC(=O)C',
			'dimethyl ketone' : 'CC(=O)C',
			'dimethyl hydantoin' : 'CC(=O)NC(=O)N',
			'ethanoyl chloride' : 'CC(=O)Cl',
			'1,2-dichloroethene' : 'C(=CCl)Cl',
			'dioform' : 'C(=CCl)Cl',
			'equisetic acid' : 'C(C(=CC(=O)O)C(=O)O)C(=O)O',
			'citridic acid' : 'C(C(=O)O)C(CC(=O)O)(C(=O)O)O',
			'acrylic aldehyde' : 'C=CC=O',
			'propenal' : 'C=CC=O',
			'propenoic acid' : 'O=C(O)C=C',
			'vinyl cyanide' : 'C=CC#N',
			'hexandioc acid' : 'C(CCC(=O)O)CC(=O)O',
			'adipinic acid' : 'C(CCC(=O)O)CC(=O)O',
			'adrenaline' : 'CNCC(C1=CC(=C(C=C1)O)O)O',
			'1-suprarenine' : 'CNCC(C1=CC(=C(C=C1)O)O)O',
			'2-hydroxybutyraldehyde' : 'CC(CC=O)O',
			'anthraquinoic acid' : 'C1=CC=C2C(=C1)C(=O)C3=CC=CC=C3C2=O',
			'propen-1-ol-3' : 'C=CCO',
			'propenyl alcohol' : 'C=CCO',
			'3-bromo-propene-1' : 'C=CCBr',
			'3-chloro-propene-1' : 'C=CCCl',
			'mustard oil' : 'CCCC[SnH](CCCC)CCCC.C(=N)=S',
			'aminodracylic acid' : 'C1=CC(=CC=C1C(=O)O)N',
			'2-aminophenol' : 'C1=CC=C(C(=C1)N)O',
			'3-aminophenol' : 'C1=CC(=CC(=C1)O)N',
			'p-hydroxyaniline' : 'C1=CC(=CC(=C1)O)N',
			'common amyl acetate' : 'CCCCCOC(C)=O',
			'α-Me-Bu-acetate' : 'CCCCCOC(C)=O',
			'di Et-carbinol acetate' : 'CCCCCOC(C)=O',
			'pentanol-1' : 'CCCCCO',
			'pentanol-2' : 'CCCC(C)O',
			'2-methyl-butanol-4' : 'CCC(C)CO',
			'3-amino pentane' : 'C1=CC(=CC=C1N)O',
			'1-bromopentane' : 'CCCCCBr',
			'1-chloropentane' : 'CCCCCCl',
			'2-chloropentane' : 'CCCC(C)Cl',
			'3-chloropentane' : 'CCC(CC)Cl',
			'1-iodopentane' : 'CCCCCI',
			'2-iodopentane' : 'CCCC(C)I',
			'pentanthiol-1' : 'CCCCCS',
			'pentanthiol-2' : 'CCCC(C)S',
			'pentanthiol' : 'CCC(C)CS',
			'pentaphen' : 'C1=CC=C(C=C1)O',
			'pentene-1' : 'CCCC=C',
			'2-methyl-butene-1' : 'CCC(=C)C',
			'pentene-2' : 'CCC=CC',
			'2-methyl-butene-2' : 'CC=C(C)C',
			'p-propenyl anisole' : 'CC=CC1=CC=C(C=C1)OC',
			'amino benzene' : 'C1=CC=C(C=C1)N',
			'phenyl amine' : 'C1=CC=C(C=C1)N',
			'cyanol' : 'C1=CC=C(C=C1)N',
			'aniline salt' : 'C1=CC=C(C=C1)N.Cl',
			'aniline chloride' : 'C1=CC=C(C=C1)N.Cl',
			'MeO-benzalacetone' : 'CC(=O)C=CC1=CC=C(C=C1)OC',
			'2-amino-anisole' : 'COC1=CC=C(C=C1)N',
			'4-amino anisole' : 'COC1=CC=CC=C1N',
			'methyl phenyl ether' : 'COC1=CC=CC=C1',
			'paranaphthalene' : 'C1=CC=C2C=C3C=CC=CC3=CC2=C1',
			'anthracin green oil' : 'C1=CC=C2C=C3C=CC=CC3=CC2=C1',
			'apiole' : 'COC1=C2C(=C(C(=C1)CC=C)OC)OCO2',
			'anthranil' : 'C1=CC2=CON=C2C=C1',
			'diphenyleneketone' : 'C1=CC=C2C(=C1)C3=CC=CC=C3C2=O',
			'phenyl chloroform' : 'C1=CC=C(C=C1)CCO',
			'eicosanoic acid' : 'CCCCCCCCCCCCCCCCCCCC(=O)O',
			'arsanilic acid' : 'C1=CC(=CC=C1N)[As](=O)(O)O',
			'arachidic acid' : 'CCCCCCCCCCCCCCCCCCCC(=O)O',
			'auramine' : 'CN(C)C1=CC=C(C=C1)C(=N)C2=CC=C(C=C2)N(C)C',
			'diphenyldiimide' : 'C1=CC=C(C=C1)N=NC2=CC=CC=C2',
			'malonyl urea' : 'C1C(=O)NC(=O)NC1=O',
			'benzal acetone' : 'CC(=O)CCC1=CC=CC=C1',
			'Me-cinnamyl ketone' : 'CC(=O)CCC1=CC=CC=C1',
			'artificial almond oil' : 'C1=CC=C(C=C1)C=O',
			'benzol' : 'C1=CC=CC=C1',
			'phenyl hydride' : 'C1=CC=CC=C1',
			'cyclohexatriene' : 'C1=CC=CC=C1',
			'dibenzoyl' : 'C1=CC=C(C=C1)C(=O)C(=O)C2=CC=CC=C2',
			'phenyl cyanide' : 'C1=CC=C(C=C1)C#N',
			'diphenyl ketone' : 'C1=CC=C(C=C1)C(=O)C2=CC=CC=C2',
			'allophanamide' : 'C(=O)(N)NC(=O)N',
			'phenyl bromide' : 'C1=CC=C(C=C1)CBr',
			'trimethyl-methane' : 'CCCC',
			'butanol-2' : 'CCC(C)O',
			'2-methyl-propanol-1' : 'CC(C)CO',
			'1-bromobutane' : 'CCCCBr',
			'2-bromo-butane' : 'CCC(C)Br',
			'carbamate' : 'C(=O)(N)[O-]',
			'1-chloro-butane' : 'CCCCCl',
			'2-chloro-butane' : 'CCC(C)Cl',
			'1-iodo-butane' : 'CCCCI',
			'2-iodo-butane' : 'CCC(C)I',
			'butanthiol-1' : 'CCCCS',
			'butyl mustard oil' : 'CCCCN=C=S',
			'butene-1' : 'CCC=C',
			'butene-2' : 'CC=CC',
			'butanoic acid' : 'CCCC(=O)O',
			'decanoic acid' : 'CCCCCCCCCC(=O)O',
			'hexanoic acid' : 'CCCCCC(=O)O',
			'octanoic acid' : 'CCCCCCCC(=O)O',
			'diphenylenelimine' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N2',
			'dibenzopyrrole' : 'C1=CC=C2C(=C1)C3=CC=CC=C3N2',
			'tetrabromomethane' : 'C(Br)(Br)(Br)Br',
			'tetrachloromethane' : 'C(Cl)(Cl)(Cl)Cl',
			'tetrafluoromethane' : 'C(F)(F)(F)F',
			'carvacrylamine' : 'c1(cc(ccc1C)C(C)C)NC1=NCCO1',
			'chloretone' : 'CC(C)(C(Cl)(Cl)Cl)O',
			'4-Chloro-acetanilide' : 'CC(=O)NC1=CC=C(C=C1)Cl',
			'chrysene' : 'C1=CC=C2C(=C1)C=CC3=C2C=CC4=CC=CC=C43',
			'chrysoidine' : 'C1=CC=C(C=C1)N=NC2=C(C=C(C=C2)N)N.Cl',
			'chrysophanic acid' : 'CC1=CC(=C2C(=C1)C(=O)C3=C(C2=O)C(=CC=C3)O)O',
			'cinchomeronic acid' : 'C1=CN=CC(=C1C(=O)O)C(=O)O',
			'cineole' : 'CC1(C2CCC(O1)(CC2)C)C',
			'eucalyptole' : 'CC1(C2CCC(O1)(CC2)C)C',
			'citraconic acid' : 'CC(=CC(=O)O)C(=O)O',
			'citronellol' : 'CC(CCC=C(C)C)CCO',
			'coumaric acid' : 'C1=CC(=CC=C1C=CC(=O)O)O',
			'coumarone' : 'C1=CC=C2C(=C1)C=CO2',
			'crotonic acid' : 'CC=CC(=O)O',
			'cumic acid' : 'CC(C)C1=CC=C(C=C1)C(=O)O',
			'cumidine sulfate' : 'CC(C)C1=CC=C(C=C1)N.CC(C)C1=CC=C(C=C1)N.OS(=O)(=O)O',
			'cyanamide' : 'C(#N)N',
			'cyanic acid' : 'C(#N)O',
			'cyanoacetic acid' : 'C(C#N)C(=O)O',
			'cystine' : 'C(C(C(=O)O)N)SSCC(C(=O)O)N',
			'cambose' : 'C1(C(C(C(C(C1O)O)O)O)O)O',
			'cecyl alcohol' : 'CCCCCCCCCCO',
			'ciacetone alcohol' : 'CC(=O)CC(C)(C)O',
			'4,4-diamino-benzophenone' : 'C1=CC(=CC=C1C(=O)C2=CC=C(C=C2)N)N',
			'dipentylamine' : 'CCCCCNCCCCC',
			'diamyl ketone' : 'CCCCCC(=O)CCCCC',
			'dibenzothiazyl-disulfide' : 'C1=CC=C2C(=C1)N=C(S2)SSC3=NC4=CC=CC=C4S3',
			'dibensoyl methane' : 'C1=CC=C(C=C1)C(=O)CC(=O)C2=CC=CC=C2',
			'dibenzylamine' : 'C1=CC=C(C=C1)CNCC2=CC=CC=C2',
			'1,2dibromobenzene' : 'C1=CC=C(C(=C1)Br)Br',
			'dichloramine' : 'CC1=CC=C(C=C1)S(=O)(=O)N(Cl)Cl',
			'dicyandiamide' : 'C(#N)N=C(N)N',
			'diethyl malonate' : 'CCOC(=O)CC(=O)OCC',
			'1,4-dimethoxy benzene' : 'COC1=CC=C(C=C1)OC',
			'dipentene' : 'CC1=CCC(CC1)C(=C)C',
			'ethylenediamine' : 'C(CN)N',
			'ditolyl guanidine' : 'CC1=CC=CC=C1NC(=NC2=CC=CC=C2C)N',
			'divinyl acetylene' : 'C=CC#CC=C',
			'dulcitol' : 'C(C(C(C(C(CO)O)O)O)O)O',
			'dlaidic acid' : 'CCCCCCCCC=CCCCCCCCC(=O)O',
			'dosine' : 'C1=CC=C(C(=C1)C2=C3C=C(C(=O)C(=C3OC4=C(C(=C(C=C24)Br)[O-])Br)Br)Br)C(=O)[O-].[Na+].[Na+]',
			'dpichlorhydrin' : 'C1C(O1)CCl',
			'ether' : 'CC(C)(C)COC',
			'bromoethane' : 'CCBr' ,
			'ethylene bromohydrin' : 'C(CBr)O',
			'2-chloroethyl bromide' : 'C(CBr)Cl',
			'2-chloroethanol' : 'C(CCl)O',
			'hexamethylbenzene' : 'CC1=C(C(=C(C(=C1C)C)C)C)C',
			'ethylene diamine' : 'C(CN)N',
			'ethylidene diacetate' : 'CC(OC(=O)C)OC(=O)C',
			'fenchyl alcohol' : 'CC1(C2CCC(C2)(C1O)C)C',
			'ferric dimethyldithiocarbamate' : 'CN(C)C(=S)[S-].CN(C)C(=S)[S-].[Fe+2]',
			'fulminic acid' : 'C#[N+][O-]',
			'furfuran' : 'C1=COC=C1',
			'furfuryl acetate alcohol' : 'CC(=O)OCC1=CC=CO1',
			'butyrate' : 'CCCC(=O)[O-]',
			'furfuryl propionate' : 'CCC(=O)OCC1=CC=CO1',
			'furoic acid' : 'C1=COC(=C1)C(=O)O',
			'gallic acid' : 'C1=C(C=C(C(=C1O)O)O)C(=O)O',
			'gamma acid' : 'C1=CC(=CC2=C(C=C(C=C21)S(=O)(=O)O)O)N',
			'glycerol diacetate' : 'CC(=O)OCC(CO)OC(=O)C',
			'glycerol nitrate' : 'C(C(CO[N+](=O)[O-])O[N+](=O)[O-])O[N+](=O)[O-]',
			'glyceryl dinitrate' : 'C(C(CO[N+](=O)[O-])O)O[N+](=O)[O-]',
			'homophthalic acid' : 'C1=CC=C(C(=C1)CC(=O)O)C(=O)O',
			'glycocoll' : 'C(C(=O)O)N',
			'diethyleneglycoldibenzoate' : 'C1=CC=C(C=C1)C(=O)OCCOCCOC(=O)C2=CC=CC=C2',
			'ethyleneglycoldibutyrate' : 'CCCC(=O)O.CCCC(=O)O.C(CO)O',
			'propyleneglycoldicaprylate' : 'CCCCCCCC(=O)OCC(C)OC(=O)CCCCCCC',
			'ethyleneglycoldiformate' : 'C(COC=O)OC=O',
			'glycol dilaurate' : 'CCCCCCCCCCCC(=O)OCCOC(=O)CCCCCCCCCCC',
			'ethylenedinitrate' : 'C(CO[N+](=O)[O-])O[N+](=O)[O-]',
			'diethyleneglycol dinitrate' : 'C(CO[N+](=O)[O-])OCCO[N+](=O)[O-]',
			'glycolpalmitate' : 'CCCCCCCCCCCCCCCC(=O)OCCO',
			'propyleneglycol dipropionate' : 'CCC(=O)OCC(C)OC(=O)CC',
			'diethyleneglycolmonoethyl ether' : 'CCOCCOCCO',
			'glycol formal' : 'C1COCO1',
			'glycol formate' : 'C(COC=O)O',
			'heptacosane' : 'CCCCCCCCCCCCCCCCCCCCCCCCCCC',
			'heptoic acid' : 'CCCCCCC(=O)O',
			'hexaethylbenzene' : 'CCC1=C(C(=C(C(=C1CC)CC)CC)CC)CC',
			'moronic acid' : 'O=C2C([C@@H]1CC[C@@]4([C@@H]([C@@]1(C)CC2)CC[C@@H]5/C3=C/C(C)(C)CC[C@]3(C(=O)O)CC[C@@]45C)C)(C)C',
    }.get(input,input)  # add new parameter if input not found

